# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

alias k='kubectl'
alias ksys='kubectl --namespace=kube-system'
alias ka='kubectl apply --recursive -f'
alias ksysa='kubectl --namespace=kube-system apply --recursive -f'
alias kak='kubectl apply -k'
alias kk='kubectl kustomize'
alias kex='kubectl exec -i -t'
alias ksysex='kubectl --namespace=kube-system exec -i -t'
alias klo='kubectl logs -f'
alias ksyslo='kubectl --namespace=kube-system logs -f'
alias klop='kubectl logs -f -p'
alias ksyslop='kubectl --namespace=kube-system logs -f -p'
alias kp='kubectl proxy'
alias kpf='kubectl port-forward'
alias kg='kubectl get'
alias ksysg='kubectl --namespace=kube-system get'
alias kd='kubectl describe'
alias ksysd='kubectl --namespace=kube-system describe'
alias krm='kubectl delete'
alias ksysrm='kubectl --namespace=kube-system delete'
alias krun='kubectl run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t'
alias ksysrun='kubectl --namespace=kube-system run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t'
alias kgpo='kubectl get pods'
alias ksysgpo='kubectl --namespace=kube-system get pods'
alias kdpo='kubectl describe pods'
alias ksysdpo='kubectl --namespace=kube-system describe pods'
alias krmpo='kubectl delete pods'
alias ksysrmpo='kubectl --namespace=kube-system delete pods'
alias kgdep='kubectl get deployment'
alias ksysgdep='kubectl --namespace=kube-system get deployment'
alias kddep='kubectl describe deployment'
alias ksysddep='kubectl --namespace=kube-system describe deployment'
alias krmdep='kubectl delete deployment'
alias ksysrmdep='kubectl --namespace=kube-system delete deployment'
alias kgss='kubectl get statefulset'
alias ksysgss='kubectl --namespace=kube-system get statefulset'
alias kdss='kubectl describe statefulset'
alias ksysdss='kubectl --namespace=kube-system describe statefulset'
alias krmss='kubectl delete statefulset'
alias ksysrmss='kubectl --namespace=kube-system delete statefulset'
alias kgds='kubectl get daemonset'
alias ksysgds='kubectl --namespace=kube-system get daemonset'
alias kdds='kubectl describe daemonset'
alias ksysdds='kubectl --namespace=kube-system describe daemonset'
alias krmds='kubectl delete daemonset'
alias ksysrmds='kubectl --namespace=kube-system delete daemonset'
alias kgjob='kubectl get job'
alias ksysgjob='kubectl --namespace=kube-system get job'
alias kdjob='kubectl describe job'
alias ksysdjob='kubectl --namespace=kube-system describe job'
alias krmjob='kubectl delete job'
alias ksysrmjob='kubectl --namespace=kube-system delete job'
alias kgcjob='kubectl get cronjob'
alias ksysgcjob='kubectl --namespace=kube-system get cronjob'
alias kdcjob='kubectl describe cronjob'
alias ksysdcjob='kubectl --namespace=kube-system describe cronjob'
alias krmcjob='kubectl delete cronjob'
alias ksysrmcjob='kubectl --namespace=kube-system delete cronjob'
alias kgsvc='kubectl get service'
alias ksysgsvc='kubectl --namespace=kube-system get service'
alias kdsvc='kubectl describe service'
alias ksysdsvc='kubectl --namespace=kube-system describe service'
alias krmsvc='kubectl delete service'
alias ksysrmsvc='kubectl --namespace=kube-system delete service'
alias kging='kubectl get ingress'
alias ksysging='kubectl --namespace=kube-system get ingress'
alias kding='kubectl describe ingress'
alias ksysding='kubectl --namespace=kube-system describe ingress'
alias krming='kubectl delete ingress'
alias ksysrming='kubectl --namespace=kube-system delete ingress'
alias kgcm='kubectl get configmap'
alias ksysgcm='kubectl --namespace=kube-system get configmap'
alias kdcm='kubectl describe configmap'
alias ksysdcm='kubectl --namespace=kube-system describe configmap'
alias krmcm='kubectl delete configmap'
alias ksysrmcm='kubectl --namespace=kube-system delete configmap'
alias kgsec='kubectl get secret'
alias ksysgsec='kubectl --namespace=kube-system get secret'
alias kdsec='kubectl describe secret'
alias ksysdsec='kubectl --namespace=kube-system describe secret'
alias krmsec='kubectl delete secret'
alias ksysrmsec='kubectl --namespace=kube-system delete secret'
alias kgsc='kubectl get storageclass'
alias ksysgsc='kubectl --namespace=kube-system get storageclass'
alias kdsc='kubectl describe storageclass'
alias ksysdsc='kubectl --namespace=kube-system describe storageclass'
alias krmsc='kubectl delete storageclass'
alias ksysrmsc='kubectl --namespace=kube-system delete storageclass'
alias kgpv='kubectl get persistentvolume'
alias ksysgpv='kubectl --namespace=kube-system get persistentvolume'
alias kdpv='kubectl describe persistentvolume'
alias ksysdpv='kubectl --namespace=kube-system describe persistentvolume'
alias krmpv='kubectl delete persistentvolume'
alias ksysrmpv='kubectl --namespace=kube-system delete persistentvolume'
alias kgpvc='kubectl get persistentvolumeclaim'
alias ksysgpvc='kubectl --namespace=kube-system get persistentvolumeclaim'
alias kdpvc='kubectl describe persistentvolumeclaim'
alias ksysdpvc='kubectl --namespace=kube-system describe persistentvolumeclaim'
alias krmpvc='kubectl delete persistentvolumeclaim'
alias ksysrmpvc='kubectl --namespace=kube-system delete persistentvolumeclaim'
alias kgva='kubectl get volumeattachment'
alias ksysgva='kubectl --namespace=kube-system get volumeattachment'
alias kdva='kubectl describe volumeattachment'
alias ksysdva='kubectl --namespace=kube-system describe volumeattachment'
alias krmva='kubectl delete volumeattachment'
alias ksysrmva='kubectl --namespace=kube-system delete volumeattachment'
alias kgno='kubectl get nodes'
alias kdno='kubectl describe nodes'
alias krmno='kubectl delete nodes'
alias kgns='kubectl get namespaces'
alias kdns='kubectl describe namespaces'
alias krmns='kubectl delete namespaces'
alias kgoyaml='kubectl get -o=yaml'
alias ksysgoyaml='kubectl --namespace=kube-system get -o=yaml'
alias kgpooyaml='kubectl get pods -o=yaml'
alias ksysgpooyaml='kubectl --namespace=kube-system get pods -o=yaml'
alias kgdepoyaml='kubectl get deployment -o=yaml'
alias ksysgdepoyaml='kubectl --namespace=kube-system get deployment -o=yaml'
alias kgssoyaml='kubectl get statefulset -o=yaml'
alias ksysgssoyaml='kubectl --namespace=kube-system get statefulset -o=yaml'
alias kgdsoyaml='kubectl get daemonset -o=yaml'
alias ksysgdsoyaml='kubectl --namespace=kube-system get daemonset -o=yaml'
alias kgjoboyaml='kubectl get job -o=yaml'
alias ksysgjoboyaml='kubectl --namespace=kube-system get job -o=yaml'
alias kgcjoboyaml='kubectl get cronjob -o=yaml'
alias ksysgcjoboyaml='kubectl --namespace=kube-system get cronjob -o=yaml'
alias kgsvcoyaml='kubectl get service -o=yaml'
alias ksysgsvcoyaml='kubectl --namespace=kube-system get service -o=yaml'
alias kgingoyaml='kubectl get ingress -o=yaml'
alias ksysgingoyaml='kubectl --namespace=kube-system get ingress -o=yaml'
alias kgcmoyaml='kubectl get configmap -o=yaml'
alias ksysgcmoyaml='kubectl --namespace=kube-system get configmap -o=yaml'
alias kgsecoyaml='kubectl get secret -o=yaml'
alias ksysgsecoyaml='kubectl --namespace=kube-system get secret -o=yaml'
alias kgscoyaml='kubectl get storageclass -o=yaml'
alias ksysgscoyaml='kubectl --namespace=kube-system get storageclass -o=yaml'
alias kgpvoyaml='kubectl get persistentvolume -o=yaml'
alias ksysgpvoyaml='kubectl --namespace=kube-system get persistentvolume -o=yaml'
alias kgpvcoyaml='kubectl get persistentvolumeclaim -o=yaml'
alias ksysgpvcoyaml='kubectl --namespace=kube-system get persistentvolumeclaim -o=yaml'
alias kgvaoyaml='kubectl get volumeattachment -o=yaml'
alias ksysgvaoyaml='kubectl --namespace=kube-system get volumeattachment -o=yaml'
alias kgnooyaml='kubectl get nodes -o=yaml'
alias kgnsoyaml='kubectl get namespaces -o=yaml'
alias kgowide='kubectl get -o=wide'
alias ksysgowide='kubectl --namespace=kube-system get -o=wide'
alias kgpoowide='kubectl get pods -o=wide'
alias ksysgpoowide='kubectl --namespace=kube-system get pods -o=wide'
alias kgdepowide='kubectl get deployment -o=wide'
alias ksysgdepowide='kubectl --namespace=kube-system get deployment -o=wide'
alias kgssowide='kubectl get statefulset -o=wide'
alias ksysgssowide='kubectl --namespace=kube-system get statefulset -o=wide'
alias kgdsowide='kubectl get daemonset -o=wide'
alias ksysgdsowide='kubectl --namespace=kube-system get daemonset -o=wide'
alias kgjobowide='kubectl get job -o=wide'
alias ksysgjobowide='kubectl --namespace=kube-system get job -o=wide'
alias kgcjobowide='kubectl get cronjob -o=wide'
alias ksysgcjobowide='kubectl --namespace=kube-system get cronjob -o=wide'
alias kgsvcowide='kubectl get service -o=wide'
alias ksysgsvcowide='kubectl --namespace=kube-system get service -o=wide'
alias kgingowide='kubectl get ingress -o=wide'
alias ksysgingowide='kubectl --namespace=kube-system get ingress -o=wide'
alias kgcmowide='kubectl get configmap -o=wide'
alias ksysgcmowide='kubectl --namespace=kube-system get configmap -o=wide'
alias kgsecowide='kubectl get secret -o=wide'
alias ksysgsecowide='kubectl --namespace=kube-system get secret -o=wide'
alias kgscowide='kubectl get storageclass -o=wide'
alias ksysgscowide='kubectl --namespace=kube-system get storageclass -o=wide'
alias kgpvowide='kubectl get persistentvolume -o=wide'
alias ksysgpvowide='kubectl --namespace=kube-system get persistentvolume -o=wide'
alias kgpvcowide='kubectl get persistentvolumeclaim -o=wide'
alias ksysgpvcowide='kubectl --namespace=kube-system get persistentvolumeclaim -o=wide'
alias kgvaowide='kubectl get volumeattachment -o=wide'
alias ksysgvaowide='kubectl --namespace=kube-system get volumeattachment -o=wide'
alias kgnoowide='kubectl get nodes -o=wide'
alias kgnsowide='kubectl get namespaces -o=wide'
alias kgojson='kubectl get -o=json'
alias ksysgojson='kubectl --namespace=kube-system get -o=json'
alias kgpoojson='kubectl get pods -o=json'
alias ksysgpoojson='kubectl --namespace=kube-system get pods -o=json'
alias kgdepojson='kubectl get deployment -o=json'
alias ksysgdepojson='kubectl --namespace=kube-system get deployment -o=json'
alias kgssojson='kubectl get statefulset -o=json'
alias ksysgssojson='kubectl --namespace=kube-system get statefulset -o=json'
alias kgdsojson='kubectl get daemonset -o=json'
alias ksysgdsojson='kubectl --namespace=kube-system get daemonset -o=json'
alias kgjobojson='kubectl get job -o=json'
alias ksysgjobojson='kubectl --namespace=kube-system get job -o=json'
alias kgcjobojson='kubectl get cronjob -o=json'
alias ksysgcjobojson='kubectl --namespace=kube-system get cronjob -o=json'
alias kgsvcojson='kubectl get service -o=json'
alias ksysgsvcojson='kubectl --namespace=kube-system get service -o=json'
alias kgingojson='kubectl get ingress -o=json'
alias ksysgingojson='kubectl --namespace=kube-system get ingress -o=json'
alias kgcmojson='kubectl get configmap -o=json'
alias ksysgcmojson='kubectl --namespace=kube-system get configmap -o=json'
alias kgsecojson='kubectl get secret -o=json'
alias ksysgsecojson='kubectl --namespace=kube-system get secret -o=json'
alias kgscojson='kubectl get storageclass -o=json'
alias ksysgscojson='kubectl --namespace=kube-system get storageclass -o=json'
alias kgpvojson='kubectl get persistentvolume -o=json'
alias ksysgpvojson='kubectl --namespace=kube-system get persistentvolume -o=json'
alias kgpvcojson='kubectl get persistentvolumeclaim -o=json'
alias ksysgpvcojson='kubectl --namespace=kube-system get persistentvolumeclaim -o=json'
alias kgvaojson='kubectl get volumeattachment -o=json'
alias ksysgvaojson='kubectl --namespace=kube-system get volumeattachment -o=json'
alias kgnoojson='kubectl get nodes -o=json'
alias kgnsojson='kubectl get namespaces -o=json'
alias kgall='kubectl get --all-namespaces'
alias kdall='kubectl describe --all-namespaces'
alias kgpoall='kubectl get pods --all-namespaces'
alias kdpoall='kubectl describe pods --all-namespaces'
alias kgdepall='kubectl get deployment --all-namespaces'
alias kddepall='kubectl describe deployment --all-namespaces'
alias kgssall='kubectl get statefulset --all-namespaces'
alias kdssall='kubectl describe statefulset --all-namespaces'
alias kgdsall='kubectl get daemonset --all-namespaces'
alias kddsall='kubectl describe daemonset --all-namespaces'
alias kgjoball='kubectl get job --all-namespaces'
alias kdjoball='kubectl describe job --all-namespaces'
alias kgcjoball='kubectl get cronjob --all-namespaces'
alias kdcjoball='kubectl describe cronjob --all-namespaces'
alias kgsvcall='kubectl get service --all-namespaces'
alias kdsvcall='kubectl describe service --all-namespaces'
alias kgingall='kubectl get ingress --all-namespaces'
alias kdingall='kubectl describe ingress --all-namespaces'
alias kgcmall='kubectl get configmap --all-namespaces'
alias kdcmall='kubectl describe configmap --all-namespaces'
alias kgsecall='kubectl get secret --all-namespaces'
alias kdsecall='kubectl describe secret --all-namespaces'
alias kgscall='kubectl get storageclass --all-namespaces'
alias kdscall='kubectl describe storageclass --all-namespaces'
alias kgpvall='kubectl get persistentvolume --all-namespaces'
alias kdpvall='kubectl describe persistentvolume --all-namespaces'
alias kgpvcall='kubectl get persistentvolumeclaim --all-namespaces'
alias kdpvcall='kubectl describe persistentvolumeclaim --all-namespaces'
alias kgvaall='kubectl get volumeattachment --all-namespaces'
alias kdvaall='kubectl describe volumeattachment --all-namespaces'
alias kgsl='kubectl get --show-labels'
alias ksysgsl='kubectl --namespace=kube-system get --show-labels'
alias kgposl='kubectl get pods --show-labels'
alias ksysgposl='kubectl --namespace=kube-system get pods --show-labels'
alias kgdepsl='kubectl get deployment --show-labels'
alias ksysgdepsl='kubectl --namespace=kube-system get deployment --show-labels'
alias kgsssl='kubectl get statefulset --show-labels'
alias ksysgsssl='kubectl --namespace=kube-system get statefulset --show-labels'
alias kgdssl='kubectl get daemonset --show-labels'
alias ksysgdssl='kubectl --namespace=kube-system get daemonset --show-labels'
alias kgjobsl='kubectl get job --show-labels'
alias ksysgjobsl='kubectl --namespace=kube-system get job --show-labels'
alias kgcjobsl='kubectl get cronjob --show-labels'
alias ksysgcjobsl='kubectl --namespace=kube-system get cronjob --show-labels'
alias kgsvcsl='kubectl get service --show-labels'
alias ksysgsvcsl='kubectl --namespace=kube-system get service --show-labels'
alias kgingsl='kubectl get ingress --show-labels'
alias ksysgingsl='kubectl --namespace=kube-system get ingress --show-labels'
alias kgcmsl='kubectl get configmap --show-labels'
alias ksysgcmsl='kubectl --namespace=kube-system get configmap --show-labels'
alias kgsecsl='kubectl get secret --show-labels'
alias ksysgsecsl='kubectl --namespace=kube-system get secret --show-labels'
alias kgscsl='kubectl get storageclass --show-labels'
alias ksysgscsl='kubectl --namespace=kube-system get storageclass --show-labels'
alias kgpvsl='kubectl get persistentvolume --show-labels'
alias ksysgpvsl='kubectl --namespace=kube-system get persistentvolume --show-labels'
alias kgpvcsl='kubectl get persistentvolumeclaim --show-labels'
alias ksysgpvcsl='kubectl --namespace=kube-system get persistentvolumeclaim --show-labels'
alias kgvasl='kubectl get volumeattachment --show-labels'
alias ksysgvasl='kubectl --namespace=kube-system get volumeattachment --show-labels'
alias kgnosl='kubectl get nodes --show-labels'
alias kgnssl='kubectl get namespaces --show-labels'
alias krmall='kubectl delete --all'
alias ksysrmall='kubectl --namespace=kube-system delete --all'
alias krmpoall='kubectl delete pods --all'
alias ksysrmpoall='kubectl --namespace=kube-system delete pods --all'
alias krmdepall='kubectl delete deployment --all'
alias ksysrmdepall='kubectl --namespace=kube-system delete deployment --all'
alias krmssall='kubectl delete statefulset --all'
alias ksysrmssall='kubectl --namespace=kube-system delete statefulset --all'
alias krmdsall='kubectl delete daemonset --all'
alias ksysrmdsall='kubectl --namespace=kube-system delete daemonset --all'
alias krmjoball='kubectl delete job --all'
alias ksysrmjoball='kubectl --namespace=kube-system delete job --all'
alias krmcjoball='kubectl delete cronjob --all'
alias ksysrmcjoball='kubectl --namespace=kube-system delete cronjob --all'
alias krmsvcall='kubectl delete service --all'
alias ksysrmsvcall='kubectl --namespace=kube-system delete service --all'
alias krmingall='kubectl delete ingress --all'
alias ksysrmingall='kubectl --namespace=kube-system delete ingress --all'
alias krmcmall='kubectl delete configmap --all'
alias ksysrmcmall='kubectl --namespace=kube-system delete configmap --all'
alias krmsecall='kubectl delete secret --all'
alias ksysrmsecall='kubectl --namespace=kube-system delete secret --all'
alias krmscall='kubectl delete storageclass --all'
alias ksysrmscall='kubectl --namespace=kube-system delete storageclass --all'
alias krmpvall='kubectl delete persistentvolume --all'
alias ksysrmpvall='kubectl --namespace=kube-system delete persistentvolume --all'
alias krmpvcall='kubectl delete persistentvolumeclaim --all'
alias ksysrmpvcall='kubectl --namespace=kube-system delete persistentvolumeclaim --all'
alias krmvaall='kubectl delete volumeattachment --all'
alias ksysrmvaall='kubectl --namespace=kube-system delete volumeattachment --all'
alias krmnoall='kubectl delete nodes --all'
alias krmnsall='kubectl delete namespaces --all'
alias kgw='kubectl get --watch'
alias ksysgw='kubectl --namespace=kube-system get --watch'
alias kgpow='kubectl get pods --watch'
alias ksysgpow='kubectl --namespace=kube-system get pods --watch'
alias kgdepw='kubectl get deployment --watch'
alias ksysgdepw='kubectl --namespace=kube-system get deployment --watch'
alias kgssw='kubectl get statefulset --watch'
alias ksysgssw='kubectl --namespace=kube-system get statefulset --watch'
alias kgdsw='kubectl get daemonset --watch'
alias ksysgdsw='kubectl --namespace=kube-system get daemonset --watch'
alias kgjobw='kubectl get job --watch'
alias ksysgjobw='kubectl --namespace=kube-system get job --watch'
alias kgcjobw='kubectl get cronjob --watch'
alias ksysgcjobw='kubectl --namespace=kube-system get cronjob --watch'
alias kgsvcw='kubectl get service --watch'
alias ksysgsvcw='kubectl --namespace=kube-system get service --watch'
alias kgingw='kubectl get ingress --watch'
alias ksysgingw='kubectl --namespace=kube-system get ingress --watch'
alias kgcmw='kubectl get configmap --watch'
alias ksysgcmw='kubectl --namespace=kube-system get configmap --watch'
alias kgsecw='kubectl get secret --watch'
alias ksysgsecw='kubectl --namespace=kube-system get secret --watch'
alias kgscw='kubectl get storageclass --watch'
alias ksysgscw='kubectl --namespace=kube-system get storageclass --watch'
alias kgpvw='kubectl get persistentvolume --watch'
alias ksysgpvw='kubectl --namespace=kube-system get persistentvolume --watch'
alias kgpvcw='kubectl get persistentvolumeclaim --watch'
alias ksysgpvcw='kubectl --namespace=kube-system get persistentvolumeclaim --watch'
alias kgvaw='kubectl get volumeattachment --watch'
alias ksysgvaw='kubectl --namespace=kube-system get volumeattachment --watch'
alias kgnow='kubectl get nodes --watch'
alias kgnsw='kubectl get namespaces --watch'
alias kgoyamlall='kubectl get -o=yaml --all-namespaces'
alias kgpooyamlall='kubectl get pods -o=yaml --all-namespaces'
alias kgdepoyamlall='kubectl get deployment -o=yaml --all-namespaces'
alias kgssoyamlall='kubectl get statefulset -o=yaml --all-namespaces'
alias kgdsoyamlall='kubectl get daemonset -o=yaml --all-namespaces'
alias kgjoboyamlall='kubectl get job -o=yaml --all-namespaces'
alias kgcjoboyamlall='kubectl get cronjob -o=yaml --all-namespaces'
alias kgsvcoyamlall='kubectl get service -o=yaml --all-namespaces'
alias kgingoyamlall='kubectl get ingress -o=yaml --all-namespaces'
alias kgcmoyamlall='kubectl get configmap -o=yaml --all-namespaces'
alias kgsecoyamlall='kubectl get secret -o=yaml --all-namespaces'
alias kgscoyamlall='kubectl get storageclass -o=yaml --all-namespaces'
alias kgpvoyamlall='kubectl get persistentvolume -o=yaml --all-namespaces'
alias kgpvcoyamlall='kubectl get persistentvolumeclaim -o=yaml --all-namespaces'
alias kgvaoyamlall='kubectl get volumeattachment -o=yaml --all-namespaces'
alias kgalloyaml='kubectl get --all-namespaces -o=yaml'
alias kgpoalloyaml='kubectl get pods --all-namespaces -o=yaml'
alias kgdepalloyaml='kubectl get deployment --all-namespaces -o=yaml'
alias kgssalloyaml='kubectl get statefulset --all-namespaces -o=yaml'
alias kgdsalloyaml='kubectl get daemonset --all-namespaces -o=yaml'
alias kgjoballoyaml='kubectl get job --all-namespaces -o=yaml'
alias kgcjoballoyaml='kubectl get cronjob --all-namespaces -o=yaml'
alias kgsvcalloyaml='kubectl get service --all-namespaces -o=yaml'
alias kgingalloyaml='kubectl get ingress --all-namespaces -o=yaml'
alias kgcmalloyaml='kubectl get configmap --all-namespaces -o=yaml'
alias kgsecalloyaml='kubectl get secret --all-namespaces -o=yaml'
alias kgscalloyaml='kubectl get storageclass --all-namespaces -o=yaml'
alias kgpvalloyaml='kubectl get persistentvolume --all-namespaces -o=yaml'
alias kgpvcalloyaml='kubectl get persistentvolumeclaim --all-namespaces -o=yaml'
alias kgvaalloyaml='kubectl get volumeattachment --all-namespaces -o=yaml'
alias kgowideall='kubectl get -o=wide --all-namespaces'
alias kgpoowideall='kubectl get pods -o=wide --all-namespaces'
alias kgdepowideall='kubectl get deployment -o=wide --all-namespaces'
alias kgssowideall='kubectl get statefulset -o=wide --all-namespaces'
alias kgdsowideall='kubectl get daemonset -o=wide --all-namespaces'
alias kgjobowideall='kubectl get job -o=wide --all-namespaces'
alias kgcjobowideall='kubectl get cronjob -o=wide --all-namespaces'
alias kgsvcowideall='kubectl get service -o=wide --all-namespaces'
alias kgingowideall='kubectl get ingress -o=wide --all-namespaces'
alias kgcmowideall='kubectl get configmap -o=wide --all-namespaces'
alias kgsecowideall='kubectl get secret -o=wide --all-namespaces'
alias kgscowideall='kubectl get storageclass -o=wide --all-namespaces'
alias kgpvowideall='kubectl get persistentvolume -o=wide --all-namespaces'
alias kgpvcowideall='kubectl get persistentvolumeclaim -o=wide --all-namespaces'
alias kgvaowideall='kubectl get volumeattachment -o=wide --all-namespaces'
alias kgallowide='kubectl get --all-namespaces -o=wide'
alias kgpoallowide='kubectl get pods --all-namespaces -o=wide'
alias kgdepallowide='kubectl get deployment --all-namespaces -o=wide'
alias kgssallowide='kubectl get statefulset --all-namespaces -o=wide'
alias kgdsallowide='kubectl get daemonset --all-namespaces -o=wide'
alias kgjoballowide='kubectl get job --all-namespaces -o=wide'
alias kgcjoballowide='kubectl get cronjob --all-namespaces -o=wide'
alias kgsvcallowide='kubectl get service --all-namespaces -o=wide'
alias kgingallowide='kubectl get ingress --all-namespaces -o=wide'
alias kgcmallowide='kubectl get configmap --all-namespaces -o=wide'
alias kgsecallowide='kubectl get secret --all-namespaces -o=wide'
alias kgscallowide='kubectl get storageclass --all-namespaces -o=wide'
alias kgpvallowide='kubectl get persistentvolume --all-namespaces -o=wide'
alias kgpvcallowide='kubectl get persistentvolumeclaim --all-namespaces -o=wide'
alias kgvaallowide='kubectl get volumeattachment --all-namespaces -o=wide'
alias kgowidesl='kubectl get -o=wide --show-labels'
alias ksysgowidesl='kubectl --namespace=kube-system get -o=wide --show-labels'
alias kgpoowidesl='kubectl get pods -o=wide --show-labels'
alias ksysgpoowidesl='kubectl --namespace=kube-system get pods -o=wide --show-labels'
alias kgdepowidesl='kubectl get deployment -o=wide --show-labels'
alias ksysgdepowidesl='kubectl --namespace=kube-system get deployment -o=wide --show-labels'
alias kgssowidesl='kubectl get statefulset -o=wide --show-labels'
alias ksysgssowidesl='kubectl --namespace=kube-system get statefulset -o=wide --show-labels'
alias kgdsowidesl='kubectl get daemonset -o=wide --show-labels'
alias ksysgdsowidesl='kubectl --namespace=kube-system get daemonset -o=wide --show-labels'
alias kgjobowidesl='kubectl get job -o=wide --show-labels'
alias ksysgjobowidesl='kubectl --namespace=kube-system get job -o=wide --show-labels'
alias kgcjobowidesl='kubectl get cronjob -o=wide --show-labels'
alias ksysgcjobowidesl='kubectl --namespace=kube-system get cronjob -o=wide --show-labels'
alias kgsvcowidesl='kubectl get service -o=wide --show-labels'
alias ksysgsvcowidesl='kubectl --namespace=kube-system get service -o=wide --show-labels'
alias kgingowidesl='kubectl get ingress -o=wide --show-labels'
alias ksysgingowidesl='kubectl --namespace=kube-system get ingress -o=wide --show-labels'
alias kgcmowidesl='kubectl get configmap -o=wide --show-labels'
alias ksysgcmowidesl='kubectl --namespace=kube-system get configmap -o=wide --show-labels'
alias kgsecowidesl='kubectl get secret -o=wide --show-labels'
alias ksysgsecowidesl='kubectl --namespace=kube-system get secret -o=wide --show-labels'
alias kgscowidesl='kubectl get storageclass -o=wide --show-labels'
alias ksysgscowidesl='kubectl --namespace=kube-system get storageclass -o=wide --show-labels'
alias kgpvowidesl='kubectl get persistentvolume -o=wide --show-labels'
alias ksysgpvowidesl='kubectl --namespace=kube-system get persistentvolume -o=wide --show-labels'
alias kgpvcowidesl='kubectl get persistentvolumeclaim -o=wide --show-labels'
alias ksysgpvcowidesl='kubectl --namespace=kube-system get persistentvolumeclaim -o=wide --show-labels'
alias kgvaowidesl='kubectl get volumeattachment -o=wide --show-labels'
alias ksysgvaowidesl='kubectl --namespace=kube-system get volumeattachment -o=wide --show-labels'
alias kgnoowidesl='kubectl get nodes -o=wide --show-labels'
alias kgnsowidesl='kubectl get namespaces -o=wide --show-labels'
alias kgslowide='kubectl get --show-labels -o=wide'
alias ksysgslowide='kubectl --namespace=kube-system get --show-labels -o=wide'
alias kgposlowide='kubectl get pods --show-labels -o=wide'
alias ksysgposlowide='kubectl --namespace=kube-system get pods --show-labels -o=wide'
alias kgdepslowide='kubectl get deployment --show-labels -o=wide'
alias ksysgdepslowide='kubectl --namespace=kube-system get deployment --show-labels -o=wide'
alias kgssslowide='kubectl get statefulset --show-labels -o=wide'
alias ksysgssslowide='kubectl --namespace=kube-system get statefulset --show-labels -o=wide'
alias kgdsslowide='kubectl get daemonset --show-labels -o=wide'
alias ksysgdsslowide='kubectl --namespace=kube-system get daemonset --show-labels -o=wide'
alias kgjobslowide='kubectl get job --show-labels -o=wide'
alias ksysgjobslowide='kubectl --namespace=kube-system get job --show-labels -o=wide'
alias kgcjobslowide='kubectl get cronjob --show-labels -o=wide'
alias ksysgcjobslowide='kubectl --namespace=kube-system get cronjob --show-labels -o=wide'
alias kgsvcslowide='kubectl get service --show-labels -o=wide'
alias ksysgsvcslowide='kubectl --namespace=kube-system get service --show-labels -o=wide'
alias kgingslowide='kubectl get ingress --show-labels -o=wide'
alias ksysgingslowide='kubectl --namespace=kube-system get ingress --show-labels -o=wide'
alias kgcmslowide='kubectl get configmap --show-labels -o=wide'
alias ksysgcmslowide='kubectl --namespace=kube-system get configmap --show-labels -o=wide'
alias kgsecslowide='kubectl get secret --show-labels -o=wide'
alias ksysgsecslowide='kubectl --namespace=kube-system get secret --show-labels -o=wide'
alias kgscslowide='kubectl get storageclass --show-labels -o=wide'
alias ksysgscslowide='kubectl --namespace=kube-system get storageclass --show-labels -o=wide'
alias kgpvslowide='kubectl get persistentvolume --show-labels -o=wide'
alias ksysgpvslowide='kubectl --namespace=kube-system get persistentvolume --show-labels -o=wide'
alias kgpvcslowide='kubectl get persistentvolumeclaim --show-labels -o=wide'
alias ksysgpvcslowide='kubectl --namespace=kube-system get persistentvolumeclaim --show-labels -o=wide'
alias kgvaslowide='kubectl get volumeattachment --show-labels -o=wide'
alias ksysgvaslowide='kubectl --namespace=kube-system get volumeattachment --show-labels -o=wide'
alias kgnoslowide='kubectl get nodes --show-labels -o=wide'
alias kgnsslowide='kubectl get namespaces --show-labels -o=wide'
alias kgojsonall='kubectl get -o=json --all-namespaces'
alias kgpoojsonall='kubectl get pods -o=json --all-namespaces'
alias kgdepojsonall='kubectl get deployment -o=json --all-namespaces'
alias kgssojsonall='kubectl get statefulset -o=json --all-namespaces'
alias kgdsojsonall='kubectl get daemonset -o=json --all-namespaces'
alias kgjobojsonall='kubectl get job -o=json --all-namespaces'
alias kgcjobojsonall='kubectl get cronjob -o=json --all-namespaces'
alias kgsvcojsonall='kubectl get service -o=json --all-namespaces'
alias kgingojsonall='kubectl get ingress -o=json --all-namespaces'
alias kgcmojsonall='kubectl get configmap -o=json --all-namespaces'
alias kgsecojsonall='kubectl get secret -o=json --all-namespaces'
alias kgscojsonall='kubectl get storageclass -o=json --all-namespaces'
alias kgpvojsonall='kubectl get persistentvolume -o=json --all-namespaces'
alias kgpvcojsonall='kubectl get persistentvolumeclaim -o=json --all-namespaces'
alias kgvaojsonall='kubectl get volumeattachment -o=json --all-namespaces'
alias kgallojson='kubectl get --all-namespaces -o=json'
alias kgpoallojson='kubectl get pods --all-namespaces -o=json'
alias kgdepallojson='kubectl get deployment --all-namespaces -o=json'
alias kgssallojson='kubectl get statefulset --all-namespaces -o=json'
alias kgdsallojson='kubectl get daemonset --all-namespaces -o=json'
alias kgjoballojson='kubectl get job --all-namespaces -o=json'
alias kgcjoballojson='kubectl get cronjob --all-namespaces -o=json'
alias kgsvcallojson='kubectl get service --all-namespaces -o=json'
alias kgingallojson='kubectl get ingress --all-namespaces -o=json'
alias kgcmallojson='kubectl get configmap --all-namespaces -o=json'
alias kgsecallojson='kubectl get secret --all-namespaces -o=json'
alias kgscallojson='kubectl get storageclass --all-namespaces -o=json'
alias kgpvallojson='kubectl get persistentvolume --all-namespaces -o=json'
alias kgpvcallojson='kubectl get persistentvolumeclaim --all-namespaces -o=json'
alias kgvaallojson='kubectl get volumeattachment --all-namespaces -o=json'
alias kgallsl='kubectl get --all-namespaces --show-labels'
alias kgpoallsl='kubectl get pods --all-namespaces --show-labels'
alias kgdepallsl='kubectl get deployment --all-namespaces --show-labels'
alias kgssallsl='kubectl get statefulset --all-namespaces --show-labels'
alias kgdsallsl='kubectl get daemonset --all-namespaces --show-labels'
alias kgjoballsl='kubectl get job --all-namespaces --show-labels'
alias kgcjoballsl='kubectl get cronjob --all-namespaces --show-labels'
alias kgsvcallsl='kubectl get service --all-namespaces --show-labels'
alias kgingallsl='kubectl get ingress --all-namespaces --show-labels'
alias kgcmallsl='kubectl get configmap --all-namespaces --show-labels'
alias kgsecallsl='kubectl get secret --all-namespaces --show-labels'
alias kgscallsl='kubectl get storageclass --all-namespaces --show-labels'
alias kgpvallsl='kubectl get persistentvolume --all-namespaces --show-labels'
alias kgpvcallsl='kubectl get persistentvolumeclaim --all-namespaces --show-labels'
alias kgvaallsl='kubectl get volumeattachment --all-namespaces --show-labels'
alias kgslall='kubectl get --show-labels --all-namespaces'
alias kgposlall='kubectl get pods --show-labels --all-namespaces'
alias kgdepslall='kubectl get deployment --show-labels --all-namespaces'
alias kgssslall='kubectl get statefulset --show-labels --all-namespaces'
alias kgdsslall='kubectl get daemonset --show-labels --all-namespaces'
alias kgjobslall='kubectl get job --show-labels --all-namespaces'
alias kgcjobslall='kubectl get cronjob --show-labels --all-namespaces'
alias kgsvcslall='kubectl get service --show-labels --all-namespaces'
alias kgingslall='kubectl get ingress --show-labels --all-namespaces'
alias kgcmslall='kubectl get configmap --show-labels --all-namespaces'
alias kgsecslall='kubectl get secret --show-labels --all-namespaces'
alias kgscslall='kubectl get storageclass --show-labels --all-namespaces'
alias kgpvslall='kubectl get persistentvolume --show-labels --all-namespaces'
alias kgpvcslall='kubectl get persistentvolumeclaim --show-labels --all-namespaces'
alias kgvaslall='kubectl get volumeattachment --show-labels --all-namespaces'
alias kgallw='kubectl get --all-namespaces --watch'
alias kgpoallw='kubectl get pods --all-namespaces --watch'
alias kgdepallw='kubectl get deployment --all-namespaces --watch'
alias kgssallw='kubectl get statefulset --all-namespaces --watch'
alias kgdsallw='kubectl get daemonset --all-namespaces --watch'
alias kgjoballw='kubectl get job --all-namespaces --watch'
alias kgcjoballw='kubectl get cronjob --all-namespaces --watch'
alias kgsvcallw='kubectl get service --all-namespaces --watch'
alias kgingallw='kubectl get ingress --all-namespaces --watch'
alias kgcmallw='kubectl get configmap --all-namespaces --watch'
alias kgsecallw='kubectl get secret --all-namespaces --watch'
alias kgscallw='kubectl get storageclass --all-namespaces --watch'
alias kgpvallw='kubectl get persistentvolume --all-namespaces --watch'
alias kgpvcallw='kubectl get persistentvolumeclaim --all-namespaces --watch'
alias kgvaallw='kubectl get volumeattachment --all-namespaces --watch'
alias kgwall='kubectl get --watch --all-namespaces'
alias kgpowall='kubectl get pods --watch --all-namespaces'
alias kgdepwall='kubectl get deployment --watch --all-namespaces'
alias kgsswall='kubectl get statefulset --watch --all-namespaces'
alias kgdswall='kubectl get daemonset --watch --all-namespaces'
alias kgjobwall='kubectl get job --watch --all-namespaces'
alias kgcjobwall='kubectl get cronjob --watch --all-namespaces'
alias kgsvcwall='kubectl get service --watch --all-namespaces'
alias kgingwall='kubectl get ingress --watch --all-namespaces'
alias kgcmwall='kubectl get configmap --watch --all-namespaces'
alias kgsecwall='kubectl get secret --watch --all-namespaces'
alias kgscwall='kubectl get storageclass --watch --all-namespaces'
alias kgpvwall='kubectl get persistentvolume --watch --all-namespaces'
alias kgpvcwall='kubectl get persistentvolumeclaim --watch --all-namespaces'
alias kgvawall='kubectl get volumeattachment --watch --all-namespaces'
alias kgslw='kubectl get --show-labels --watch'
alias ksysgslw='kubectl --namespace=kube-system get --show-labels --watch'
alias kgposlw='kubectl get pods --show-labels --watch'
alias ksysgposlw='kubectl --namespace=kube-system get pods --show-labels --watch'
alias kgdepslw='kubectl get deployment --show-labels --watch'
alias ksysgdepslw='kubectl --namespace=kube-system get deployment --show-labels --watch'
alias kgssslw='kubectl get statefulset --show-labels --watch'
alias ksysgssslw='kubectl --namespace=kube-system get statefulset --show-labels --watch'
alias kgdsslw='kubectl get daemonset --show-labels --watch'
alias ksysgdsslw='kubectl --namespace=kube-system get daemonset --show-labels --watch'
alias kgjobslw='kubectl get job --show-labels --watch'
alias ksysgjobslw='kubectl --namespace=kube-system get job --show-labels --watch'
alias kgcjobslw='kubectl get cronjob --show-labels --watch'
alias ksysgcjobslw='kubectl --namespace=kube-system get cronjob --show-labels --watch'
alias kgsvcslw='kubectl get service --show-labels --watch'
alias ksysgsvcslw='kubectl --namespace=kube-system get service --show-labels --watch'
alias kgingslw='kubectl get ingress --show-labels --watch'
alias ksysgingslw='kubectl --namespace=kube-system get ingress --show-labels --watch'
alias kgcmslw='kubectl get configmap --show-labels --watch'
alias ksysgcmslw='kubectl --namespace=kube-system get configmap --show-labels --watch'
alias kgsecslw='kubectl get secret --show-labels --watch'
alias ksysgsecslw='kubectl --namespace=kube-system get secret --show-labels --watch'
alias kgscslw='kubectl get storageclass --show-labels --watch'
alias ksysgscslw='kubectl --namespace=kube-system get storageclass --show-labels --watch'
alias kgpvslw='kubectl get persistentvolume --show-labels --watch'
alias ksysgpvslw='kubectl --namespace=kube-system get persistentvolume --show-labels --watch'
alias kgpvcslw='kubectl get persistentvolumeclaim --show-labels --watch'
alias ksysgpvcslw='kubectl --namespace=kube-system get persistentvolumeclaim --show-labels --watch'
alias kgvaslw='kubectl get volumeattachment --show-labels --watch'
alias ksysgvaslw='kubectl --namespace=kube-system get volumeattachment --show-labels --watch'
alias kgnoslw='kubectl get nodes --show-labels --watch'
alias kgnsslw='kubectl get namespaces --show-labels --watch'
alias kgwsl='kubectl get --watch --show-labels'
alias ksysgwsl='kubectl --namespace=kube-system get --watch --show-labels'
alias kgpowsl='kubectl get pods --watch --show-labels'
alias ksysgpowsl='kubectl --namespace=kube-system get pods --watch --show-labels'
alias kgdepwsl='kubectl get deployment --watch --show-labels'
alias ksysgdepwsl='kubectl --namespace=kube-system get deployment --watch --show-labels'
alias kgsswsl='kubectl get statefulset --watch --show-labels'
alias ksysgsswsl='kubectl --namespace=kube-system get statefulset --watch --show-labels'
alias kgdswsl='kubectl get daemonset --watch --show-labels'
alias ksysgdswsl='kubectl --namespace=kube-system get daemonset --watch --show-labels'
alias kgjobwsl='kubectl get job --watch --show-labels'
alias ksysgjobwsl='kubectl --namespace=kube-system get job --watch --show-labels'
alias kgcjobwsl='kubectl get cronjob --watch --show-labels'
alias ksysgcjobwsl='kubectl --namespace=kube-system get cronjob --watch --show-labels'
alias kgsvcwsl='kubectl get service --watch --show-labels'
alias ksysgsvcwsl='kubectl --namespace=kube-system get service --watch --show-labels'
alias kgingwsl='kubectl get ingress --watch --show-labels'
alias ksysgingwsl='kubectl --namespace=kube-system get ingress --watch --show-labels'
alias kgcmwsl='kubectl get configmap --watch --show-labels'
alias ksysgcmwsl='kubectl --namespace=kube-system get configmap --watch --show-labels'
alias kgsecwsl='kubectl get secret --watch --show-labels'
alias ksysgsecwsl='kubectl --namespace=kube-system get secret --watch --show-labels'
alias kgscwsl='kubectl get storageclass --watch --show-labels'
alias ksysgscwsl='kubectl --namespace=kube-system get storageclass --watch --show-labels'
alias kgpvwsl='kubectl get persistentvolume --watch --show-labels'
alias ksysgpvwsl='kubectl --namespace=kube-system get persistentvolume --watch --show-labels'
alias kgpvcwsl='kubectl get persistentvolumeclaim --watch --show-labels'
alias ksysgpvcwsl='kubectl --namespace=kube-system get persistentvolumeclaim --watch --show-labels'
alias kgvawsl='kubectl get volumeattachment --watch --show-labels'
alias ksysgvawsl='kubectl --namespace=kube-system get volumeattachment --watch --show-labels'
alias kgnowsl='kubectl get nodes --watch --show-labels'
alias kgnswsl='kubectl get namespaces --watch --show-labels'
alias kgowideallsl='kubectl get -o=wide --all-namespaces --show-labels'
alias kgpoowideallsl='kubectl get pods -o=wide --all-namespaces --show-labels'
alias kgdepowideallsl='kubectl get deployment -o=wide --all-namespaces --show-labels'
alias kgssowideallsl='kubectl get statefulset -o=wide --all-namespaces --show-labels'
alias kgdsowideallsl='kubectl get daemonset -o=wide --all-namespaces --show-labels'
alias kgjobowideallsl='kubectl get job -o=wide --all-namespaces --show-labels'
alias kgcjobowideallsl='kubectl get cronjob -o=wide --all-namespaces --show-labels'
alias kgsvcowideallsl='kubectl get service -o=wide --all-namespaces --show-labels'
alias kgingowideallsl='kubectl get ingress -o=wide --all-namespaces --show-labels'
alias kgcmowideallsl='kubectl get configmap -o=wide --all-namespaces --show-labels'
alias kgsecowideallsl='kubectl get secret -o=wide --all-namespaces --show-labels'
alias kgscowideallsl='kubectl get storageclass -o=wide --all-namespaces --show-labels'
alias kgpvowideallsl='kubectl get persistentvolume -o=wide --all-namespaces --show-labels'
alias kgpvcowideallsl='kubectl get persistentvolumeclaim -o=wide --all-namespaces --show-labels'
alias kgvaowideallsl='kubectl get volumeattachment -o=wide --all-namespaces --show-labels'
alias kgowideslall='kubectl get -o=wide --show-labels --all-namespaces'
alias kgpoowideslall='kubectl get pods -o=wide --show-labels --all-namespaces'
alias kgdepowideslall='kubectl get deployment -o=wide --show-labels --all-namespaces'
alias kgssowideslall='kubectl get statefulset -o=wide --show-labels --all-namespaces'
alias kgdsowideslall='kubectl get daemonset -o=wide --show-labels --all-namespaces'
alias kgjobowideslall='kubectl get job -o=wide --show-labels --all-namespaces'
alias kgcjobowideslall='kubectl get cronjob -o=wide --show-labels --all-namespaces'
alias kgsvcowideslall='kubectl get service -o=wide --show-labels --all-namespaces'
alias kgingowideslall='kubectl get ingress -o=wide --show-labels --all-namespaces'
alias kgcmowideslall='kubectl get configmap -o=wide --show-labels --all-namespaces'
alias kgsecowideslall='kubectl get secret -o=wide --show-labels --all-namespaces'
alias kgscowideslall='kubectl get storageclass -o=wide --show-labels --all-namespaces'
alias kgpvowideslall='kubectl get persistentvolume -o=wide --show-labels --all-namespaces'
alias kgpvcowideslall='kubectl get persistentvolumeclaim -o=wide --show-labels --all-namespaces'
alias kgvaowideslall='kubectl get volumeattachment -o=wide --show-labels --all-namespaces'
alias kgallowidesl='kubectl get --all-namespaces -o=wide --show-labels'
alias kgpoallowidesl='kubectl get pods --all-namespaces -o=wide --show-labels'
alias kgdepallowidesl='kubectl get deployment --all-namespaces -o=wide --show-labels'
alias kgssallowidesl='kubectl get statefulset --all-namespaces -o=wide --show-labels'
alias kgdsallowidesl='kubectl get daemonset --all-namespaces -o=wide --show-labels'
alias kgjoballowidesl='kubectl get job --all-namespaces -o=wide --show-labels'
alias kgcjoballowidesl='kubectl get cronjob --all-namespaces -o=wide --show-labels'
alias kgsvcallowidesl='kubectl get service --all-namespaces -o=wide --show-labels'
alias kgingallowidesl='kubectl get ingress --all-namespaces -o=wide --show-labels'
alias kgcmallowidesl='kubectl get configmap --all-namespaces -o=wide --show-labels'
alias kgsecallowidesl='kubectl get secret --all-namespaces -o=wide --show-labels'
alias kgscallowidesl='kubectl get storageclass --all-namespaces -o=wide --show-labels'
alias kgpvallowidesl='kubectl get persistentvolume --all-namespaces -o=wide --show-labels'
alias kgpvcallowidesl='kubectl get persistentvolumeclaim --all-namespaces -o=wide --show-labels'
alias kgvaallowidesl='kubectl get volumeattachment --all-namespaces -o=wide --show-labels'
alias kgallslowide='kubectl get --all-namespaces --show-labels -o=wide'
alias kgpoallslowide='kubectl get pods --all-namespaces --show-labels -o=wide'
alias kgdepallslowide='kubectl get deployment --all-namespaces --show-labels -o=wide'
alias kgssallslowide='kubectl get statefulset --all-namespaces --show-labels -o=wide'
alias kgdsallslowide='kubectl get daemonset --all-namespaces --show-labels -o=wide'
alias kgjoballslowide='kubectl get job --all-namespaces --show-labels -o=wide'
alias kgcjoballslowide='kubectl get cronjob --all-namespaces --show-labels -o=wide'
alias kgsvcallslowide='kubectl get service --all-namespaces --show-labels -o=wide'
alias kgingallslowide='kubectl get ingress --all-namespaces --show-labels -o=wide'
alias kgcmallslowide='kubectl get configmap --all-namespaces --show-labels -o=wide'
alias kgsecallslowide='kubectl get secret --all-namespaces --show-labels -o=wide'
alias kgscallslowide='kubectl get storageclass --all-namespaces --show-labels -o=wide'
alias kgpvallslowide='kubectl get persistentvolume --all-namespaces --show-labels -o=wide'
alias kgpvcallslowide='kubectl get persistentvolumeclaim --all-namespaces --show-labels -o=wide'
alias kgvaallslowide='kubectl get volumeattachment --all-namespaces --show-labels -o=wide'
alias kgslowideall='kubectl get --show-labels -o=wide --all-namespaces'
alias kgposlowideall='kubectl get pods --show-labels -o=wide --all-namespaces'
alias kgdepslowideall='kubectl get deployment --show-labels -o=wide --all-namespaces'
alias kgssslowideall='kubectl get statefulset --show-labels -o=wide --all-namespaces'
alias kgdsslowideall='kubectl get daemonset --show-labels -o=wide --all-namespaces'
alias kgjobslowideall='kubectl get job --show-labels -o=wide --all-namespaces'
alias kgcjobslowideall='kubectl get cronjob --show-labels -o=wide --all-namespaces'
alias kgsvcslowideall='kubectl get service --show-labels -o=wide --all-namespaces'
alias kgingslowideall='kubectl get ingress --show-labels -o=wide --all-namespaces'
alias kgcmslowideall='kubectl get configmap --show-labels -o=wide --all-namespaces'
alias kgsecslowideall='kubectl get secret --show-labels -o=wide --all-namespaces'
alias kgscslowideall='kubectl get storageclass --show-labels -o=wide --all-namespaces'
alias kgpvslowideall='kubectl get persistentvolume --show-labels -o=wide --all-namespaces'
alias kgpvcslowideall='kubectl get persistentvolumeclaim --show-labels -o=wide --all-namespaces'
alias kgvaslowideall='kubectl get volumeattachment --show-labels -o=wide --all-namespaces'
alias kgslallowide='kubectl get --show-labels --all-namespaces -o=wide'
alias kgposlallowide='kubectl get pods --show-labels --all-namespaces -o=wide'
alias kgdepslallowide='kubectl get deployment --show-labels --all-namespaces -o=wide'
alias kgssslallowide='kubectl get statefulset --show-labels --all-namespaces -o=wide'
alias kgdsslallowide='kubectl get daemonset --show-labels --all-namespaces -o=wide'
alias kgjobslallowide='kubectl get job --show-labels --all-namespaces -o=wide'
alias kgcjobslallowide='kubectl get cronjob --show-labels --all-namespaces -o=wide'
alias kgsvcslallowide='kubectl get service --show-labels --all-namespaces -o=wide'
alias kgingslallowide='kubectl get ingress --show-labels --all-namespaces -o=wide'
alias kgcmslallowide='kubectl get configmap --show-labels --all-namespaces -o=wide'
alias kgsecslallowide='kubectl get secret --show-labels --all-namespaces -o=wide'
alias kgscslallowide='kubectl get storageclass --show-labels --all-namespaces -o=wide'
alias kgpvslallowide='kubectl get persistentvolume --show-labels --all-namespaces -o=wide'
alias kgpvcslallowide='kubectl get persistentvolumeclaim --show-labels --all-namespaces -o=wide'
alias kgvaslallowide='kubectl get volumeattachment --show-labels --all-namespaces -o=wide'
alias kgallslw='kubectl get --all-namespaces --show-labels --watch'
alias kgpoallslw='kubectl get pods --all-namespaces --show-labels --watch'
alias kgdepallslw='kubectl get deployment --all-namespaces --show-labels --watch'
alias kgssallslw='kubectl get statefulset --all-namespaces --show-labels --watch'
alias kgdsallslw='kubectl get daemonset --all-namespaces --show-labels --watch'
alias kgjoballslw='kubectl get job --all-namespaces --show-labels --watch'
alias kgcjoballslw='kubectl get cronjob --all-namespaces --show-labels --watch'
alias kgsvcallslw='kubectl get service --all-namespaces --show-labels --watch'
alias kgingallslw='kubectl get ingress --all-namespaces --show-labels --watch'
alias kgcmallslw='kubectl get configmap --all-namespaces --show-labels --watch'
alias kgsecallslw='kubectl get secret --all-namespaces --show-labels --watch'
alias kgscallslw='kubectl get storageclass --all-namespaces --show-labels --watch'
alias kgpvallslw='kubectl get persistentvolume --all-namespaces --show-labels --watch'
alias kgpvcallslw='kubectl get persistentvolumeclaim --all-namespaces --show-labels --watch'
alias kgvaallslw='kubectl get volumeattachment --all-namespaces --show-labels --watch'
alias kgallwsl='kubectl get --all-namespaces --watch --show-labels'
alias kgpoallwsl='kubectl get pods --all-namespaces --watch --show-labels'
alias kgdepallwsl='kubectl get deployment --all-namespaces --watch --show-labels'
alias kgssallwsl='kubectl get statefulset --all-namespaces --watch --show-labels'
alias kgdsallwsl='kubectl get daemonset --all-namespaces --watch --show-labels'
alias kgjoballwsl='kubectl get job --all-namespaces --watch --show-labels'
alias kgcjoballwsl='kubectl get cronjob --all-namespaces --watch --show-labels'
alias kgsvcallwsl='kubectl get service --all-namespaces --watch --show-labels'
alias kgingallwsl='kubectl get ingress --all-namespaces --watch --show-labels'
alias kgcmallwsl='kubectl get configmap --all-namespaces --watch --show-labels'
alias kgsecallwsl='kubectl get secret --all-namespaces --watch --show-labels'
alias kgscallwsl='kubectl get storageclass --all-namespaces --watch --show-labels'
alias kgpvallwsl='kubectl get persistentvolume --all-namespaces --watch --show-labels'
alias kgpvcallwsl='kubectl get persistentvolumeclaim --all-namespaces --watch --show-labels'
alias kgvaallwsl='kubectl get volumeattachment --all-namespaces --watch --show-labels'
alias kgslallw='kubectl get --show-labels --all-namespaces --watch'
alias kgposlallw='kubectl get pods --show-labels --all-namespaces --watch'
alias kgdepslallw='kubectl get deployment --show-labels --all-namespaces --watch'
alias kgssslallw='kubectl get statefulset --show-labels --all-namespaces --watch'
alias kgdsslallw='kubectl get daemonset --show-labels --all-namespaces --watch'
alias kgjobslallw='kubectl get job --show-labels --all-namespaces --watch'
alias kgcjobslallw='kubectl get cronjob --show-labels --all-namespaces --watch'
alias kgsvcslallw='kubectl get service --show-labels --all-namespaces --watch'
alias kgingslallw='kubectl get ingress --show-labels --all-namespaces --watch'
alias kgcmslallw='kubectl get configmap --show-labels --all-namespaces --watch'
alias kgsecslallw='kubectl get secret --show-labels --all-namespaces --watch'
alias kgscslallw='kubectl get storageclass --show-labels --all-namespaces --watch'
alias kgpvslallw='kubectl get persistentvolume --show-labels --all-namespaces --watch'
alias kgpvcslallw='kubectl get persistentvolumeclaim --show-labels --all-namespaces --watch'
alias kgvaslallw='kubectl get volumeattachment --show-labels --all-namespaces --watch'
alias kgslwall='kubectl get --show-labels --watch --all-namespaces'
alias kgposlwall='kubectl get pods --show-labels --watch --all-namespaces'
alias kgdepslwall='kubectl get deployment --show-labels --watch --all-namespaces'
alias kgssslwall='kubectl get statefulset --show-labels --watch --all-namespaces'
alias kgdsslwall='kubectl get daemonset --show-labels --watch --all-namespaces'
alias kgjobslwall='kubectl get job --show-labels --watch --all-namespaces'
alias kgcjobslwall='kubectl get cronjob --show-labels --watch --all-namespaces'
alias kgsvcslwall='kubectl get service --show-labels --watch --all-namespaces'
alias kgingslwall='kubectl get ingress --show-labels --watch --all-namespaces'
alias kgcmslwall='kubectl get configmap --show-labels --watch --all-namespaces'
alias kgsecslwall='kubectl get secret --show-labels --watch --all-namespaces'
alias kgscslwall='kubectl get storageclass --show-labels --watch --all-namespaces'
alias kgpvslwall='kubectl get persistentvolume --show-labels --watch --all-namespaces'
alias kgpvcslwall='kubectl get persistentvolumeclaim --show-labels --watch --all-namespaces'
alias kgvaslwall='kubectl get volumeattachment --show-labels --watch --all-namespaces'
alias kgwallsl='kubectl get --watch --all-namespaces --show-labels'
alias kgpowallsl='kubectl get pods --watch --all-namespaces --show-labels'
alias kgdepwallsl='kubectl get deployment --watch --all-namespaces --show-labels'
alias kgsswallsl='kubectl get statefulset --watch --all-namespaces --show-labels'
alias kgdswallsl='kubectl get daemonset --watch --all-namespaces --show-labels'
alias kgjobwallsl='kubectl get job --watch --all-namespaces --show-labels'
alias kgcjobwallsl='kubectl get cronjob --watch --all-namespaces --show-labels'
alias kgsvcwallsl='kubectl get service --watch --all-namespaces --show-labels'
alias kgingwallsl='kubectl get ingress --watch --all-namespaces --show-labels'
alias kgcmwallsl='kubectl get configmap --watch --all-namespaces --show-labels'
alias kgsecwallsl='kubectl get secret --watch --all-namespaces --show-labels'
alias kgscwallsl='kubectl get storageclass --watch --all-namespaces --show-labels'
alias kgpvwallsl='kubectl get persistentvolume --watch --all-namespaces --show-labels'
alias kgpvcwallsl='kubectl get persistentvolumeclaim --watch --all-namespaces --show-labels'
alias kgvawallsl='kubectl get volumeattachment --watch --all-namespaces --show-labels'
alias kgwslall='kubectl get --watch --show-labels --all-namespaces'
alias kgpowslall='kubectl get pods --watch --show-labels --all-namespaces'
alias kgdepwslall='kubectl get deployment --watch --show-labels --all-namespaces'
alias kgsswslall='kubectl get statefulset --watch --show-labels --all-namespaces'
alias kgdswslall='kubectl get daemonset --watch --show-labels --all-namespaces'
alias kgjobwslall='kubectl get job --watch --show-labels --all-namespaces'
alias kgcjobwslall='kubectl get cronjob --watch --show-labels --all-namespaces'
alias kgsvcwslall='kubectl get service --watch --show-labels --all-namespaces'
alias kgingwslall='kubectl get ingress --watch --show-labels --all-namespaces'
alias kgcmwslall='kubectl get configmap --watch --show-labels --all-namespaces'
alias kgsecwslall='kubectl get secret --watch --show-labels --all-namespaces'
alias kgscwslall='kubectl get storageclass --watch --show-labels --all-namespaces'
alias kgpvwslall='kubectl get persistentvolume --watch --show-labels --all-namespaces'
alias kgpvcwslall='kubectl get persistentvolumeclaim --watch --show-labels --all-namespaces'
alias kgvawslall='kubectl get volumeattachment --watch --show-labels --all-namespaces'
alias kgf='kubectl get --recursive -f'
alias kdf='kubectl describe --recursive -f'
alias krmf='kubectl delete --recursive -f'
alias kgoyamlf='kubectl get -o=yaml --recursive -f'
alias kgowidef='kubectl get -o=wide --recursive -f'
alias kgojsonf='kubectl get -o=json --recursive -f'
alias kgslf='kubectl get --show-labels --recursive -f'
alias kgwf='kubectl get --watch --recursive -f'
alias kgowideslf='kubectl get -o=wide --show-labels --recursive -f'
alias kgslowidef='kubectl get --show-labels -o=wide --recursive -f'
alias kgslwf='kubectl get --show-labels --watch --recursive -f'
alias kgwslf='kubectl get --watch --show-labels --recursive -f'
alias kgl='kubectl get -l'
alias ksysgl='kubectl --namespace=kube-system get -l'
alias kdl='kubectl describe -l'
alias ksysdl='kubectl --namespace=kube-system describe -l'
alias krml='kubectl delete -l'
alias ksysrml='kubectl --namespace=kube-system delete -l'
alias kgpol='kubectl get pods -l'
alias ksysgpol='kubectl --namespace=kube-system get pods -l'
alias kdpol='kubectl describe pods -l'
alias ksysdpol='kubectl --namespace=kube-system describe pods -l'
alias krmpol='kubectl delete pods -l'
alias ksysrmpol='kubectl --namespace=kube-system delete pods -l'
alias kgdepl='kubectl get deployment -l'
alias ksysgdepl='kubectl --namespace=kube-system get deployment -l'
alias kddepl='kubectl describe deployment -l'
alias ksysddepl='kubectl --namespace=kube-system describe deployment -l'
alias krmdepl='kubectl delete deployment -l'
alias ksysrmdepl='kubectl --namespace=kube-system delete deployment -l'
alias kgssl='kubectl get statefulset -l'
alias ksysgssl='kubectl --namespace=kube-system get statefulset -l'
alias kdssl='kubectl describe statefulset -l'
alias ksysdssl='kubectl --namespace=kube-system describe statefulset -l'
alias krmssl='kubectl delete statefulset -l'
alias ksysrmssl='kubectl --namespace=kube-system delete statefulset -l'
alias kgdsl='kubectl get daemonset -l'
alias ksysgdsl='kubectl --namespace=kube-system get daemonset -l'
alias kddsl='kubectl describe daemonset -l'
alias ksysddsl='kubectl --namespace=kube-system describe daemonset -l'
alias krmdsl='kubectl delete daemonset -l'
alias ksysrmdsl='kubectl --namespace=kube-system delete daemonset -l'
alias kgjobl='kubectl get job -l'
alias ksysgjobl='kubectl --namespace=kube-system get job -l'
alias kdjobl='kubectl describe job -l'
alias ksysdjobl='kubectl --namespace=kube-system describe job -l'
alias krmjobl='kubectl delete job -l'
alias ksysrmjobl='kubectl --namespace=kube-system delete job -l'
alias kgcjobl='kubectl get cronjob -l'
alias ksysgcjobl='kubectl --namespace=kube-system get cronjob -l'
alias kdcjobl='kubectl describe cronjob -l'
alias ksysdcjobl='kubectl --namespace=kube-system describe cronjob -l'
alias krmcjobl='kubectl delete cronjob -l'
alias ksysrmcjobl='kubectl --namespace=kube-system delete cronjob -l'
alias kgsvcl='kubectl get service -l'
alias ksysgsvcl='kubectl --namespace=kube-system get service -l'
alias kdsvcl='kubectl describe service -l'
alias ksysdsvcl='kubectl --namespace=kube-system describe service -l'
alias krmsvcl='kubectl delete service -l'
alias ksysrmsvcl='kubectl --namespace=kube-system delete service -l'
alias kgingl='kubectl get ingress -l'
alias ksysgingl='kubectl --namespace=kube-system get ingress -l'
alias kdingl='kubectl describe ingress -l'
alias ksysdingl='kubectl --namespace=kube-system describe ingress -l'
alias krmingl='kubectl delete ingress -l'
alias ksysrmingl='kubectl --namespace=kube-system delete ingress -l'
alias kgcml='kubectl get configmap -l'
alias ksysgcml='kubectl --namespace=kube-system get configmap -l'
alias kdcml='kubectl describe configmap -l'
alias ksysdcml='kubectl --namespace=kube-system describe configmap -l'
alias krmcml='kubectl delete configmap -l'
alias ksysrmcml='kubectl --namespace=kube-system delete configmap -l'
alias kgsecl='kubectl get secret -l'
alias ksysgsecl='kubectl --namespace=kube-system get secret -l'
alias kdsecl='kubectl describe secret -l'
alias ksysdsecl='kubectl --namespace=kube-system describe secret -l'
alias krmsecl='kubectl delete secret -l'
alias ksysrmsecl='kubectl --namespace=kube-system delete secret -l'
alias kgscl='kubectl get storageclass -l'
alias ksysgscl='kubectl --namespace=kube-system get storageclass -l'
alias kdscl='kubectl describe storageclass -l'
alias ksysdscl='kubectl --namespace=kube-system describe storageclass -l'
alias krmscl='kubectl delete storageclass -l'
alias ksysrmscl='kubectl --namespace=kube-system delete storageclass -l'
alias kgpvl='kubectl get persistentvolume -l'
alias ksysgpvl='kubectl --namespace=kube-system get persistentvolume -l'
alias kdpvl='kubectl describe persistentvolume -l'
alias ksysdpvl='kubectl --namespace=kube-system describe persistentvolume -l'
alias krmpvl='kubectl delete persistentvolume -l'
alias ksysrmpvl='kubectl --namespace=kube-system delete persistentvolume -l'
alias kgpvcl='kubectl get persistentvolumeclaim -l'
alias ksysgpvcl='kubectl --namespace=kube-system get persistentvolumeclaim -l'
alias kdpvcl='kubectl describe persistentvolumeclaim -l'
alias ksysdpvcl='kubectl --namespace=kube-system describe persistentvolumeclaim -l'
alias krmpvcl='kubectl delete persistentvolumeclaim -l'
alias ksysrmpvcl='kubectl --namespace=kube-system delete persistentvolumeclaim -l'
alias kgval='kubectl get volumeattachment -l'
alias ksysgval='kubectl --namespace=kube-system get volumeattachment -l'
alias kdval='kubectl describe volumeattachment -l'
alias ksysdval='kubectl --namespace=kube-system describe volumeattachment -l'
alias krmval='kubectl delete volumeattachment -l'
alias ksysrmval='kubectl --namespace=kube-system delete volumeattachment -l'
alias kgnol='kubectl get nodes -l'
alias kdnol='kubectl describe nodes -l'
alias krmnol='kubectl delete nodes -l'
alias kgnsl='kubectl get namespaces -l'
alias kdnsl='kubectl describe namespaces -l'
alias krmnsl='kubectl delete namespaces -l'
alias kgoyamll='kubectl get -o=yaml -l'
alias ksysgoyamll='kubectl --namespace=kube-system get -o=yaml -l'
alias kgpooyamll='kubectl get pods -o=yaml -l'
alias ksysgpooyamll='kubectl --namespace=kube-system get pods -o=yaml -l'
alias kgdepoyamll='kubectl get deployment -o=yaml -l'
alias ksysgdepoyamll='kubectl --namespace=kube-system get deployment -o=yaml -l'
alias kgssoyamll='kubectl get statefulset -o=yaml -l'
alias ksysgssoyamll='kubectl --namespace=kube-system get statefulset -o=yaml -l'
alias kgdsoyamll='kubectl get daemonset -o=yaml -l'
alias ksysgdsoyamll='kubectl --namespace=kube-system get daemonset -o=yaml -l'
alias kgjoboyamll='kubectl get job -o=yaml -l'
alias ksysgjoboyamll='kubectl --namespace=kube-system get job -o=yaml -l'
alias kgcjoboyamll='kubectl get cronjob -o=yaml -l'
alias ksysgcjoboyamll='kubectl --namespace=kube-system get cronjob -o=yaml -l'
alias kgsvcoyamll='kubectl get service -o=yaml -l'
alias ksysgsvcoyamll='kubectl --namespace=kube-system get service -o=yaml -l'
alias kgingoyamll='kubectl get ingress -o=yaml -l'
alias ksysgingoyamll='kubectl --namespace=kube-system get ingress -o=yaml -l'
alias kgcmoyamll='kubectl get configmap -o=yaml -l'
alias ksysgcmoyamll='kubectl --namespace=kube-system get configmap -o=yaml -l'
alias kgsecoyamll='kubectl get secret -o=yaml -l'
alias ksysgsecoyamll='kubectl --namespace=kube-system get secret -o=yaml -l'
alias kgscoyamll='kubectl get storageclass -o=yaml -l'
alias ksysgscoyamll='kubectl --namespace=kube-system get storageclass -o=yaml -l'
alias kgpvoyamll='kubectl get persistentvolume -o=yaml -l'
alias ksysgpvoyamll='kubectl --namespace=kube-system get persistentvolume -o=yaml -l'
alias kgpvcoyamll='kubectl get persistentvolumeclaim -o=yaml -l'
alias ksysgpvcoyamll='kubectl --namespace=kube-system get persistentvolumeclaim -o=yaml -l'
alias kgvaoyamll='kubectl get volumeattachment -o=yaml -l'
alias ksysgvaoyamll='kubectl --namespace=kube-system get volumeattachment -o=yaml -l'
alias kgnooyamll='kubectl get nodes -o=yaml -l'
alias kgnsoyamll='kubectl get namespaces -o=yaml -l'
alias kgowidel='kubectl get -o=wide -l'
alias ksysgowidel='kubectl --namespace=kube-system get -o=wide -l'
alias kgpoowidel='kubectl get pods -o=wide -l'
alias ksysgpoowidel='kubectl --namespace=kube-system get pods -o=wide -l'
alias kgdepowidel='kubectl get deployment -o=wide -l'
alias ksysgdepowidel='kubectl --namespace=kube-system get deployment -o=wide -l'
alias kgssowidel='kubectl get statefulset -o=wide -l'
alias ksysgssowidel='kubectl --namespace=kube-system get statefulset -o=wide -l'
alias kgdsowidel='kubectl get daemonset -o=wide -l'
alias ksysgdsowidel='kubectl --namespace=kube-system get daemonset -o=wide -l'
alias kgjobowidel='kubectl get job -o=wide -l'
alias ksysgjobowidel='kubectl --namespace=kube-system get job -o=wide -l'
alias kgcjobowidel='kubectl get cronjob -o=wide -l'
alias ksysgcjobowidel='kubectl --namespace=kube-system get cronjob -o=wide -l'
alias kgsvcowidel='kubectl get service -o=wide -l'
alias ksysgsvcowidel='kubectl --namespace=kube-system get service -o=wide -l'
alias kgingowidel='kubectl get ingress -o=wide -l'
alias ksysgingowidel='kubectl --namespace=kube-system get ingress -o=wide -l'
alias kgcmowidel='kubectl get configmap -o=wide -l'
alias ksysgcmowidel='kubectl --namespace=kube-system get configmap -o=wide -l'
alias kgsecowidel='kubectl get secret -o=wide -l'
alias ksysgsecowidel='kubectl --namespace=kube-system get secret -o=wide -l'
alias kgscowidel='kubectl get storageclass -o=wide -l'
alias ksysgscowidel='kubectl --namespace=kube-system get storageclass -o=wide -l'
alias kgpvowidel='kubectl get persistentvolume -o=wide -l'
alias ksysgpvowidel='kubectl --namespace=kube-system get persistentvolume -o=wide -l'
alias kgpvcowidel='kubectl get persistentvolumeclaim -o=wide -l'
alias ksysgpvcowidel='kubectl --namespace=kube-system get persistentvolumeclaim -o=wide -l'
alias kgvaowidel='kubectl get volumeattachment -o=wide -l'
alias ksysgvaowidel='kubectl --namespace=kube-system get volumeattachment -o=wide -l'
alias kgnoowidel='kubectl get nodes -o=wide -l'
alias kgnsowidel='kubectl get namespaces -o=wide -l'
alias kgojsonl='kubectl get -o=json -l'
alias ksysgojsonl='kubectl --namespace=kube-system get -o=json -l'
alias kgpoojsonl='kubectl get pods -o=json -l'
alias ksysgpoojsonl='kubectl --namespace=kube-system get pods -o=json -l'
alias kgdepojsonl='kubectl get deployment -o=json -l'
alias ksysgdepojsonl='kubectl --namespace=kube-system get deployment -o=json -l'
alias kgssojsonl='kubectl get statefulset -o=json -l'
alias ksysgssojsonl='kubectl --namespace=kube-system get statefulset -o=json -l'
alias kgdsojsonl='kubectl get daemonset -o=json -l'
alias ksysgdsojsonl='kubectl --namespace=kube-system get daemonset -o=json -l'
alias kgjobojsonl='kubectl get job -o=json -l'
alias ksysgjobojsonl='kubectl --namespace=kube-system get job -o=json -l'
alias kgcjobojsonl='kubectl get cronjob -o=json -l'
alias ksysgcjobojsonl='kubectl --namespace=kube-system get cronjob -o=json -l'
alias kgsvcojsonl='kubectl get service -o=json -l'
alias ksysgsvcojsonl='kubectl --namespace=kube-system get service -o=json -l'
alias kgingojsonl='kubectl get ingress -o=json -l'
alias ksysgingojsonl='kubectl --namespace=kube-system get ingress -o=json -l'
alias kgcmojsonl='kubectl get configmap -o=json -l'
alias ksysgcmojsonl='kubectl --namespace=kube-system get configmap -o=json -l'
alias kgsecojsonl='kubectl get secret -o=json -l'
alias ksysgsecojsonl='kubectl --namespace=kube-system get secret -o=json -l'
alias kgscojsonl='kubectl get storageclass -o=json -l'
alias ksysgscojsonl='kubectl --namespace=kube-system get storageclass -o=json -l'
alias kgpvojsonl='kubectl get persistentvolume -o=json -l'
alias ksysgpvojsonl='kubectl --namespace=kube-system get persistentvolume -o=json -l'
alias kgpvcojsonl='kubectl get persistentvolumeclaim -o=json -l'
alias ksysgpvcojsonl='kubectl --namespace=kube-system get persistentvolumeclaim -o=json -l'
alias kgvaojsonl='kubectl get volumeattachment -o=json -l'
alias ksysgvaojsonl='kubectl --namespace=kube-system get volumeattachment -o=json -l'
alias kgnoojsonl='kubectl get nodes -o=json -l'
alias kgnsojsonl='kubectl get namespaces -o=json -l'
alias kgsll='kubectl get --show-labels -l'
alias ksysgsll='kubectl --namespace=kube-system get --show-labels -l'
alias kgposll='kubectl get pods --show-labels -l'
alias ksysgposll='kubectl --namespace=kube-system get pods --show-labels -l'
alias kgdepsll='kubectl get deployment --show-labels -l'
alias ksysgdepsll='kubectl --namespace=kube-system get deployment --show-labels -l'
alias kgsssll='kubectl get statefulset --show-labels -l'
alias ksysgsssll='kubectl --namespace=kube-system get statefulset --show-labels -l'
alias kgdssll='kubectl get daemonset --show-labels -l'
alias ksysgdssll='kubectl --namespace=kube-system get daemonset --show-labels -l'
alias kgjobsll='kubectl get job --show-labels -l'
alias ksysgjobsll='kubectl --namespace=kube-system get job --show-labels -l'
alias kgcjobsll='kubectl get cronjob --show-labels -l'
alias ksysgcjobsll='kubectl --namespace=kube-system get cronjob --show-labels -l'
alias kgsvcsll='kubectl get service --show-labels -l'
alias ksysgsvcsll='kubectl --namespace=kube-system get service --show-labels -l'
alias kgingsll='kubectl get ingress --show-labels -l'
alias ksysgingsll='kubectl --namespace=kube-system get ingress --show-labels -l'
alias kgcmsll='kubectl get configmap --show-labels -l'
alias ksysgcmsll='kubectl --namespace=kube-system get configmap --show-labels -l'
alias kgsecsll='kubectl get secret --show-labels -l'
alias ksysgsecsll='kubectl --namespace=kube-system get secret --show-labels -l'
alias kgscsll='kubectl get storageclass --show-labels -l'
alias ksysgscsll='kubectl --namespace=kube-system get storageclass --show-labels -l'
alias kgpvsll='kubectl get persistentvolume --show-labels -l'
alias ksysgpvsll='kubectl --namespace=kube-system get persistentvolume --show-labels -l'
alias kgpvcsll='kubectl get persistentvolumeclaim --show-labels -l'
alias ksysgpvcsll='kubectl --namespace=kube-system get persistentvolumeclaim --show-labels -l'
alias kgvasll='kubectl get volumeattachment --show-labels -l'
alias ksysgvasll='kubectl --namespace=kube-system get volumeattachment --show-labels -l'
alias kgnosll='kubectl get nodes --show-labels -l'
alias kgnssll='kubectl get namespaces --show-labels -l'
alias kgwl='kubectl get --watch -l'
alias ksysgwl='kubectl --namespace=kube-system get --watch -l'
alias kgpowl='kubectl get pods --watch -l'
alias ksysgpowl='kubectl --namespace=kube-system get pods --watch -l'
alias kgdepwl='kubectl get deployment --watch -l'
alias ksysgdepwl='kubectl --namespace=kube-system get deployment --watch -l'
alias kgsswl='kubectl get statefulset --watch -l'
alias ksysgsswl='kubectl --namespace=kube-system get statefulset --watch -l'
alias kgdswl='kubectl get daemonset --watch -l'
alias ksysgdswl='kubectl --namespace=kube-system get daemonset --watch -l'
alias kgjobwl='kubectl get job --watch -l'
alias ksysgjobwl='kubectl --namespace=kube-system get job --watch -l'
alias kgcjobwl='kubectl get cronjob --watch -l'
alias ksysgcjobwl='kubectl --namespace=kube-system get cronjob --watch -l'
alias kgsvcwl='kubectl get service --watch -l'
alias ksysgsvcwl='kubectl --namespace=kube-system get service --watch -l'
alias kgingwl='kubectl get ingress --watch -l'
alias ksysgingwl='kubectl --namespace=kube-system get ingress --watch -l'
alias kgcmwl='kubectl get configmap --watch -l'
alias ksysgcmwl='kubectl --namespace=kube-system get configmap --watch -l'
alias kgsecwl='kubectl get secret --watch -l'
alias ksysgsecwl='kubectl --namespace=kube-system get secret --watch -l'
alias kgscwl='kubectl get storageclass --watch -l'
alias ksysgscwl='kubectl --namespace=kube-system get storageclass --watch -l'
alias kgpvwl='kubectl get persistentvolume --watch -l'
alias ksysgpvwl='kubectl --namespace=kube-system get persistentvolume --watch -l'
alias kgpvcwl='kubectl get persistentvolumeclaim --watch -l'
alias ksysgpvcwl='kubectl --namespace=kube-system get persistentvolumeclaim --watch -l'
alias kgvawl='kubectl get volumeattachment --watch -l'
alias ksysgvawl='kubectl --namespace=kube-system get volumeattachment --watch -l'
alias kgnowl='kubectl get nodes --watch -l'
alias kgnswl='kubectl get namespaces --watch -l'
alias kgowidesll='kubectl get -o=wide --show-labels -l'
alias ksysgowidesll='kubectl --namespace=kube-system get -o=wide --show-labels -l'
alias kgpoowidesll='kubectl get pods -o=wide --show-labels -l'
alias ksysgpoowidesll='kubectl --namespace=kube-system get pods -o=wide --show-labels -l'
alias kgdepowidesll='kubectl get deployment -o=wide --show-labels -l'
alias ksysgdepowidesll='kubectl --namespace=kube-system get deployment -o=wide --show-labels -l'
alias kgssowidesll='kubectl get statefulset -o=wide --show-labels -l'
alias ksysgssowidesll='kubectl --namespace=kube-system get statefulset -o=wide --show-labels -l'
alias kgdsowidesll='kubectl get daemonset -o=wide --show-labels -l'
alias ksysgdsowidesll='kubectl --namespace=kube-system get daemonset -o=wide --show-labels -l'
alias kgjobowidesll='kubectl get job -o=wide --show-labels -l'
alias ksysgjobowidesll='kubectl --namespace=kube-system get job -o=wide --show-labels -l'
alias kgcjobowidesll='kubectl get cronjob -o=wide --show-labels -l'
alias ksysgcjobowidesll='kubectl --namespace=kube-system get cronjob -o=wide --show-labels -l'
alias kgsvcowidesll='kubectl get service -o=wide --show-labels -l'
alias ksysgsvcowidesll='kubectl --namespace=kube-system get service -o=wide --show-labels -l'
alias kgingowidesll='kubectl get ingress -o=wide --show-labels -l'
alias ksysgingowidesll='kubectl --namespace=kube-system get ingress -o=wide --show-labels -l'
alias kgcmowidesll='kubectl get configmap -o=wide --show-labels -l'
alias ksysgcmowidesll='kubectl --namespace=kube-system get configmap -o=wide --show-labels -l'
alias kgsecowidesll='kubectl get secret -o=wide --show-labels -l'
alias ksysgsecowidesll='kubectl --namespace=kube-system get secret -o=wide --show-labels -l'
alias kgscowidesll='kubectl get storageclass -o=wide --show-labels -l'
alias ksysgscowidesll='kubectl --namespace=kube-system get storageclass -o=wide --show-labels -l'
alias kgpvowidesll='kubectl get persistentvolume -o=wide --show-labels -l'
alias ksysgpvowidesll='kubectl --namespace=kube-system get persistentvolume -o=wide --show-labels -l'
alias kgpvcowidesll='kubectl get persistentvolumeclaim -o=wide --show-labels -l'
alias ksysgpvcowidesll='kubectl --namespace=kube-system get persistentvolumeclaim -o=wide --show-labels -l'
alias kgvaowidesll='kubectl get volumeattachment -o=wide --show-labels -l'
alias ksysgvaowidesll='kubectl --namespace=kube-system get volumeattachment -o=wide --show-labels -l'
alias kgnoowidesll='kubectl get nodes -o=wide --show-labels -l'
alias kgnsowidesll='kubectl get namespaces -o=wide --show-labels -l'
alias kgslowidel='kubectl get --show-labels -o=wide -l'
alias ksysgslowidel='kubectl --namespace=kube-system get --show-labels -o=wide -l'
alias kgposlowidel='kubectl get pods --show-labels -o=wide -l'
alias ksysgposlowidel='kubectl --namespace=kube-system get pods --show-labels -o=wide -l'
alias kgdepslowidel='kubectl get deployment --show-labels -o=wide -l'
alias ksysgdepslowidel='kubectl --namespace=kube-system get deployment --show-labels -o=wide -l'
alias kgssslowidel='kubectl get statefulset --show-labels -o=wide -l'
alias ksysgssslowidel='kubectl --namespace=kube-system get statefulset --show-labels -o=wide -l'
alias kgdsslowidel='kubectl get daemonset --show-labels -o=wide -l'
alias ksysgdsslowidel='kubectl --namespace=kube-system get daemonset --show-labels -o=wide -l'
alias kgjobslowidel='kubectl get job --show-labels -o=wide -l'
alias ksysgjobslowidel='kubectl --namespace=kube-system get job --show-labels -o=wide -l'
alias kgcjobslowidel='kubectl get cronjob --show-labels -o=wide -l'
alias ksysgcjobslowidel='kubectl --namespace=kube-system get cronjob --show-labels -o=wide -l'
alias kgsvcslowidel='kubectl get service --show-labels -o=wide -l'
alias ksysgsvcslowidel='kubectl --namespace=kube-system get service --show-labels -o=wide -l'
alias kgingslowidel='kubectl get ingress --show-labels -o=wide -l'
alias ksysgingslowidel='kubectl --namespace=kube-system get ingress --show-labels -o=wide -l'
alias kgcmslowidel='kubectl get configmap --show-labels -o=wide -l'
alias ksysgcmslowidel='kubectl --namespace=kube-system get configmap --show-labels -o=wide -l'
alias kgsecslowidel='kubectl get secret --show-labels -o=wide -l'
alias ksysgsecslowidel='kubectl --namespace=kube-system get secret --show-labels -o=wide -l'
alias kgscslowidel='kubectl get storageclass --show-labels -o=wide -l'
alias ksysgscslowidel='kubectl --namespace=kube-system get storageclass --show-labels -o=wide -l'
alias kgpvslowidel='kubectl get persistentvolume --show-labels -o=wide -l'
alias ksysgpvslowidel='kubectl --namespace=kube-system get persistentvolume --show-labels -o=wide -l'
alias kgpvcslowidel='kubectl get persistentvolumeclaim --show-labels -o=wide -l'
alias ksysgpvcslowidel='kubectl --namespace=kube-system get persistentvolumeclaim --show-labels -o=wide -l'
alias kgvaslowidel='kubectl get volumeattachment --show-labels -o=wide -l'
alias ksysgvaslowidel='kubectl --namespace=kube-system get volumeattachment --show-labels -o=wide -l'
alias kgnoslowidel='kubectl get nodes --show-labels -o=wide -l'
alias kgnsslowidel='kubectl get namespaces --show-labels -o=wide -l'
alias kgslwl='kubectl get --show-labels --watch -l'
alias ksysgslwl='kubectl --namespace=kube-system get --show-labels --watch -l'
alias kgposlwl='kubectl get pods --show-labels --watch -l'
alias ksysgposlwl='kubectl --namespace=kube-system get pods --show-labels --watch -l'
alias kgdepslwl='kubectl get deployment --show-labels --watch -l'
alias ksysgdepslwl='kubectl --namespace=kube-system get deployment --show-labels --watch -l'
alias kgssslwl='kubectl get statefulset --show-labels --watch -l'
alias ksysgssslwl='kubectl --namespace=kube-system get statefulset --show-labels --watch -l'
alias kgdsslwl='kubectl get daemonset --show-labels --watch -l'
alias ksysgdsslwl='kubectl --namespace=kube-system get daemonset --show-labels --watch -l'
alias kgjobslwl='kubectl get job --show-labels --watch -l'
alias ksysgjobslwl='kubectl --namespace=kube-system get job --show-labels --watch -l'
alias kgcjobslwl='kubectl get cronjob --show-labels --watch -l'
alias ksysgcjobslwl='kubectl --namespace=kube-system get cronjob --show-labels --watch -l'
alias kgsvcslwl='kubectl get service --show-labels --watch -l'
alias ksysgsvcslwl='kubectl --namespace=kube-system get service --show-labels --watch -l'
alias kgingslwl='kubectl get ingress --show-labels --watch -l'
alias ksysgingslwl='kubectl --namespace=kube-system get ingress --show-labels --watch -l'
alias kgcmslwl='kubectl get configmap --show-labels --watch -l'
alias ksysgcmslwl='kubectl --namespace=kube-system get configmap --show-labels --watch -l'
alias kgsecslwl='kubectl get secret --show-labels --watch -l'
alias ksysgsecslwl='kubectl --namespace=kube-system get secret --show-labels --watch -l'
alias kgscslwl='kubectl get storageclass --show-labels --watch -l'
alias ksysgscslwl='kubectl --namespace=kube-system get storageclass --show-labels --watch -l'
alias kgpvslwl='kubectl get persistentvolume --show-labels --watch -l'
alias ksysgpvslwl='kubectl --namespace=kube-system get persistentvolume --show-labels --watch -l'
alias kgpvcslwl='kubectl get persistentvolumeclaim --show-labels --watch -l'
alias ksysgpvcslwl='kubectl --namespace=kube-system get persistentvolumeclaim --show-labels --watch -l'
alias kgvaslwl='kubectl get volumeattachment --show-labels --watch -l'
alias ksysgvaslwl='kubectl --namespace=kube-system get volumeattachment --show-labels --watch -l'
alias kgnoslwl='kubectl get nodes --show-labels --watch -l'
alias kgnsslwl='kubectl get namespaces --show-labels --watch -l'
alias kgwsll='kubectl get --watch --show-labels -l'
alias ksysgwsll='kubectl --namespace=kube-system get --watch --show-labels -l'
alias kgpowsll='kubectl get pods --watch --show-labels -l'
alias ksysgpowsll='kubectl --namespace=kube-system get pods --watch --show-labels -l'
alias kgdepwsll='kubectl get deployment --watch --show-labels -l'
alias ksysgdepwsll='kubectl --namespace=kube-system get deployment --watch --show-labels -l'
alias kgsswsll='kubectl get statefulset --watch --show-labels -l'
alias ksysgsswsll='kubectl --namespace=kube-system get statefulset --watch --show-labels -l'
alias kgdswsll='kubectl get daemonset --watch --show-labels -l'
alias ksysgdswsll='kubectl --namespace=kube-system get daemonset --watch --show-labels -l'
alias kgjobwsll='kubectl get job --watch --show-labels -l'
alias ksysgjobwsll='kubectl --namespace=kube-system get job --watch --show-labels -l'
alias kgcjobwsll='kubectl get cronjob --watch --show-labels -l'
alias ksysgcjobwsll='kubectl --namespace=kube-system get cronjob --watch --show-labels -l'
alias kgsvcwsll='kubectl get service --watch --show-labels -l'
alias ksysgsvcwsll='kubectl --namespace=kube-system get service --watch --show-labels -l'
alias kgingwsll='kubectl get ingress --watch --show-labels -l'
alias ksysgingwsll='kubectl --namespace=kube-system get ingress --watch --show-labels -l'
alias kgcmwsll='kubectl get configmap --watch --show-labels -l'
alias ksysgcmwsll='kubectl --namespace=kube-system get configmap --watch --show-labels -l'
alias kgsecwsll='kubectl get secret --watch --show-labels -l'
alias ksysgsecwsll='kubectl --namespace=kube-system get secret --watch --show-labels -l'
alias kgscwsll='kubectl get storageclass --watch --show-labels -l'
alias ksysgscwsll='kubectl --namespace=kube-system get storageclass --watch --show-labels -l'
alias kgpvwsll='kubectl get persistentvolume --watch --show-labels -l'
alias ksysgpvwsll='kubectl --namespace=kube-system get persistentvolume --watch --show-labels -l'
alias kgpvcwsll='kubectl get persistentvolumeclaim --watch --show-labels -l'
alias ksysgpvcwsll='kubectl --namespace=kube-system get persistentvolumeclaim --watch --show-labels -l'
alias kgvawsll='kubectl get volumeattachment --watch --show-labels -l'
alias ksysgvawsll='kubectl --namespace=kube-system get volumeattachment --watch --show-labels -l'
alias kgnowsll='kubectl get nodes --watch --show-labels -l'
alias kgnswsll='kubectl get namespaces --watch --show-labels -l'
alias kexn='kubectl exec -i -t --namespace'
alias klon='kubectl logs -f --namespace'
alias kpfn='kubectl port-forward --namespace'
alias kgn='kubectl get --namespace'
alias kdn='kubectl describe --namespace'
alias krmn='kubectl delete --namespace'
alias kgpon='kubectl get pods --namespace'
alias kdpon='kubectl describe pods --namespace'
alias krmpon='kubectl delete pods --namespace'
alias kgdepn='kubectl get deployment --namespace'
alias kddepn='kubectl describe deployment --namespace'
alias krmdepn='kubectl delete deployment --namespace'
alias kgssn='kubectl get statefulset --namespace'
alias kdssn='kubectl describe statefulset --namespace'
alias krmssn='kubectl delete statefulset --namespace'
alias kgdsn='kubectl get daemonset --namespace'
alias kddsn='kubectl describe daemonset --namespace'
alias krmdsn='kubectl delete daemonset --namespace'
alias kgjobn='kubectl get job --namespace'
alias kdjobn='kubectl describe job --namespace'
alias krmjobn='kubectl delete job --namespace'
alias kgcjobn='kubectl get cronjob --namespace'
alias kdcjobn='kubectl describe cronjob --namespace'
alias krmcjobn='kubectl delete cronjob --namespace'
alias kgsvcn='kubectl get service --namespace'
alias kdsvcn='kubectl describe service --namespace'
alias krmsvcn='kubectl delete service --namespace'
alias kgingn='kubectl get ingress --namespace'
alias kdingn='kubectl describe ingress --namespace'
alias krmingn='kubectl delete ingress --namespace'
alias kgcmn='kubectl get configmap --namespace'
alias kdcmn='kubectl describe configmap --namespace'
alias krmcmn='kubectl delete configmap --namespace'
alias kgsecn='kubectl get secret --namespace'
alias kdsecn='kubectl describe secret --namespace'
alias krmsecn='kubectl delete secret --namespace'
alias kgscn='kubectl get storageclass --namespace'
alias kdscn='kubectl describe storageclass --namespace'
alias krmscn='kubectl delete storageclass --namespace'
alias kgpvn='kubectl get persistentvolume --namespace'
alias kdpvn='kubectl describe persistentvolume --namespace'
alias krmpvn='kubectl delete persistentvolume --namespace'
alias kgpvcn='kubectl get persistentvolumeclaim --namespace'
alias kdpvcn='kubectl describe persistentvolumeclaim --namespace'
alias krmpvcn='kubectl delete persistentvolumeclaim --namespace'
alias kgvan='kubectl get volumeattachment --namespace'
alias kdvan='kubectl describe volumeattachment --namespace'
alias krmvan='kubectl delete volumeattachment --namespace'
alias kgoyamln='kubectl get -o=yaml --namespace'
alias kgpooyamln='kubectl get pods -o=yaml --namespace'
alias kgdepoyamln='kubectl get deployment -o=yaml --namespace'
alias kgssoyamln='kubectl get statefulset -o=yaml --namespace'
alias kgdsoyamln='kubectl get daemonset -o=yaml --namespace'
alias kgjoboyamln='kubectl get job -o=yaml --namespace'
alias kgcjoboyamln='kubectl get cronjob -o=yaml --namespace'
alias kgsvcoyamln='kubectl get service -o=yaml --namespace'
alias kgingoyamln='kubectl get ingress -o=yaml --namespace'
alias kgcmoyamln='kubectl get configmap -o=yaml --namespace'
alias kgsecoyamln='kubectl get secret -o=yaml --namespace'
alias kgscoyamln='kubectl get storageclass -o=yaml --namespace'
alias kgpvoyamln='kubectl get persistentvolume -o=yaml --namespace'
alias kgpvcoyamln='kubectl get persistentvolumeclaim -o=yaml --namespace'
alias kgvaoyamln='kubectl get volumeattachment -o=yaml --namespace'
alias kgowiden='kubectl get -o=wide --namespace'
alias kgpoowiden='kubectl get pods -o=wide --namespace'
alias kgdepowiden='kubectl get deployment -o=wide --namespace'
alias kgssowiden='kubectl get statefulset -o=wide --namespace'
alias kgdsowiden='kubectl get daemonset -o=wide --namespace'
alias kgjobowiden='kubectl get job -o=wide --namespace'
alias kgcjobowiden='kubectl get cronjob -o=wide --namespace'
alias kgsvcowiden='kubectl get service -o=wide --namespace'
alias kgingowiden='kubectl get ingress -o=wide --namespace'
alias kgcmowiden='kubectl get configmap -o=wide --namespace'
alias kgsecowiden='kubectl get secret -o=wide --namespace'
alias kgscowiden='kubectl get storageclass -o=wide --namespace'
alias kgpvowiden='kubectl get persistentvolume -o=wide --namespace'
alias kgpvcowiden='kubectl get persistentvolumeclaim -o=wide --namespace'
alias kgvaowiden='kubectl get volumeattachment -o=wide --namespace'
alias kgojsonn='kubectl get -o=json --namespace'
alias kgpoojsonn='kubectl get pods -o=json --namespace'
alias kgdepojsonn='kubectl get deployment -o=json --namespace'
alias kgssojsonn='kubectl get statefulset -o=json --namespace'
alias kgdsojsonn='kubectl get daemonset -o=json --namespace'
alias kgjobojsonn='kubectl get job -o=json --namespace'
alias kgcjobojsonn='kubectl get cronjob -o=json --namespace'
alias kgsvcojsonn='kubectl get service -o=json --namespace'
alias kgingojsonn='kubectl get ingress -o=json --namespace'
alias kgcmojsonn='kubectl get configmap -o=json --namespace'
alias kgsecojsonn='kubectl get secret -o=json --namespace'
alias kgscojsonn='kubectl get storageclass -o=json --namespace'
alias kgpvojsonn='kubectl get persistentvolume -o=json --namespace'
alias kgpvcojsonn='kubectl get persistentvolumeclaim -o=json --namespace'
alias kgvaojsonn='kubectl get volumeattachment -o=json --namespace'
alias kgsln='kubectl get --show-labels --namespace'
alias kgposln='kubectl get pods --show-labels --namespace'
alias kgdepsln='kubectl get deployment --show-labels --namespace'
alias kgsssln='kubectl get statefulset --show-labels --namespace'
alias kgdssln='kubectl get daemonset --show-labels --namespace'
alias kgjobsln='kubectl get job --show-labels --namespace'
alias kgcjobsln='kubectl get cronjob --show-labels --namespace'
alias kgsvcsln='kubectl get service --show-labels --namespace'
alias kgingsln='kubectl get ingress --show-labels --namespace'
alias kgcmsln='kubectl get configmap --show-labels --namespace'
alias kgsecsln='kubectl get secret --show-labels --namespace'
alias kgscsln='kubectl get storageclass --show-labels --namespace'
alias kgpvsln='kubectl get persistentvolume --show-labels --namespace'
alias kgpvcsln='kubectl get persistentvolumeclaim --show-labels --namespace'
alias kgvasln='kubectl get volumeattachment --show-labels --namespace'
alias kgwn='kubectl get --watch --namespace'
alias kgpown='kubectl get pods --watch --namespace'
alias kgdepwn='kubectl get deployment --watch --namespace'
alias kgsswn='kubectl get statefulset --watch --namespace'
alias kgdswn='kubectl get daemonset --watch --namespace'
alias kgjobwn='kubectl get job --watch --namespace'
alias kgcjobwn='kubectl get cronjob --watch --namespace'
alias kgsvcwn='kubectl get service --watch --namespace'
alias kgingwn='kubectl get ingress --watch --namespace'
alias kgcmwn='kubectl get configmap --watch --namespace'
alias kgsecwn='kubectl get secret --watch --namespace'
alias kgscwn='kubectl get storageclass --watch --namespace'
alias kgpvwn='kubectl get persistentvolume --watch --namespace'
alias kgpvcwn='kubectl get persistentvolumeclaim --watch --namespace'
alias kgvawn='kubectl get volumeattachment --watch --namespace'
alias kgowidesln='kubectl get -o=wide --show-labels --namespace'
alias kgpoowidesln='kubectl get pods -o=wide --show-labels --namespace'
alias kgdepowidesln='kubectl get deployment -o=wide --show-labels --namespace'
alias kgssowidesln='kubectl get statefulset -o=wide --show-labels --namespace'
alias kgdsowidesln='kubectl get daemonset -o=wide --show-labels --namespace'
alias kgjobowidesln='kubectl get job -o=wide --show-labels --namespace'
alias kgcjobowidesln='kubectl get cronjob -o=wide --show-labels --namespace'
alias kgsvcowidesln='kubectl get service -o=wide --show-labels --namespace'
alias kgingowidesln='kubectl get ingress -o=wide --show-labels --namespace'
alias kgcmowidesln='kubectl get configmap -o=wide --show-labels --namespace'
alias kgsecowidesln='kubectl get secret -o=wide --show-labels --namespace'
alias kgscowidesln='kubectl get storageclass -o=wide --show-labels --namespace'
alias kgpvowidesln='kubectl get persistentvolume -o=wide --show-labels --namespace'
alias kgpvcowidesln='kubectl get persistentvolumeclaim -o=wide --show-labels --namespace'
alias kgvaowidesln='kubectl get volumeattachment -o=wide --show-labels --namespace'
alias kgslowiden='kubectl get --show-labels -o=wide --namespace'
alias kgposlowiden='kubectl get pods --show-labels -o=wide --namespace'
alias kgdepslowiden='kubectl get deployment --show-labels -o=wide --namespace'
alias kgssslowiden='kubectl get statefulset --show-labels -o=wide --namespace'
alias kgdsslowiden='kubectl get daemonset --show-labels -o=wide --namespace'
alias kgjobslowiden='kubectl get job --show-labels -o=wide --namespace'
alias kgcjobslowiden='kubectl get cronjob --show-labels -o=wide --namespace'
alias kgsvcslowiden='kubectl get service --show-labels -o=wide --namespace'
alias kgingslowiden='kubectl get ingress --show-labels -o=wide --namespace'
alias kgcmslowiden='kubectl get configmap --show-labels -o=wide --namespace'
alias kgsecslowiden='kubectl get secret --show-labels -o=wide --namespace'
alias kgscslowiden='kubectl get storageclass --show-labels -o=wide --namespace'
alias kgpvslowiden='kubectl get persistentvolume --show-labels -o=wide --namespace'
alias kgpvcslowiden='kubectl get persistentvolumeclaim --show-labels -o=wide --namespace'
alias kgvaslowiden='kubectl get volumeattachment --show-labels -o=wide --namespace'
alias kgslwn='kubectl get --show-labels --watch --namespace'
alias kgposlwn='kubectl get pods --show-labels --watch --namespace'
alias kgdepslwn='kubectl get deployment --show-labels --watch --namespace'
alias kgssslwn='kubectl get statefulset --show-labels --watch --namespace'
alias kgdsslwn='kubectl get daemonset --show-labels --watch --namespace'
alias kgjobslwn='kubectl get job --show-labels --watch --namespace'
alias kgcjobslwn='kubectl get cronjob --show-labels --watch --namespace'
alias kgsvcslwn='kubectl get service --show-labels --watch --namespace'
alias kgingslwn='kubectl get ingress --show-labels --watch --namespace'
alias kgcmslwn='kubectl get configmap --show-labels --watch --namespace'
alias kgsecslwn='kubectl get secret --show-labels --watch --namespace'
alias kgscslwn='kubectl get storageclass --show-labels --watch --namespace'
alias kgpvslwn='kubectl get persistentvolume --show-labels --watch --namespace'
alias kgpvcslwn='kubectl get persistentvolumeclaim --show-labels --watch --namespace'
alias kgvaslwn='kubectl get volumeattachment --show-labels --watch --namespace'
alias kgwsln='kubectl get --watch --show-labels --namespace'
alias kgpowsln='kubectl get pods --watch --show-labels --namespace'
alias kgdepwsln='kubectl get deployment --watch --show-labels --namespace'
alias kgsswsln='kubectl get statefulset --watch --show-labels --namespace'
alias kgdswsln='kubectl get daemonset --watch --show-labels --namespace'
alias kgjobwsln='kubectl get job --watch --show-labels --namespace'
alias kgcjobwsln='kubectl get cronjob --watch --show-labels --namespace'
alias kgsvcwsln='kubectl get service --watch --show-labels --namespace'
alias kgingwsln='kubectl get ingress --watch --show-labels --namespace'
alias kgcmwsln='kubectl get configmap --watch --show-labels --namespace'
alias kgsecwsln='kubectl get secret --watch --show-labels --namespace'
alias kgscwsln='kubectl get storageclass --watch --show-labels --namespace'
alias kgpvwsln='kubectl get persistentvolume --watch --show-labels --namespace'
alias kgpvcwsln='kubectl get persistentvolumeclaim --watch --show-labels --namespace'
alias kgvawsln='kubectl get volumeattachment --watch --show-labels --namespace'
